### ISSUE TITLE
Troubleshooting Device Control Failure After Reconnection

### ISSUE THREAD

**Issue by joehecn** [project-chip/matter.js#1024]
```bash
(base) hemiao@hemiaodeMBP matter.js % npm run shell -- --ble

> shell
> matter-run packages/matter-node-shell.js/src/app.ts --ble

2024-07-17 17:40:14.551 INFO   Node                 Storage location: .matter-shell-0 (Directory)
Started Node #0 (Type: controller) with BLE
matter-node> commission pair --ble --pairingCode 1032-742-2419 --node-id 333
2024-07-17 17:40:24.969 INFO   Node                 matter.js shell controller started for node 0
2024-07-17 17:40:24.995 INFO   SessionManager       restoring resumption record for node 333
{"discovery":{"knownAddress":"undefined","identifierData":{"shortDiscriminator":4},"discoveryCapabilities":{"ble":true,"onIpNetwork":true}},"passcode":36719818,"commissioning":{"nodeId":"333","regulatoryLocation":1,"regulatoryCountryCode":"XX"}}
2024-07-17 17:40:25.003 INFO   MatterController     Commissioning device with identifier {"shortDiscriminator":4} and 2 scanners and knownAddress "undefined"
2024-07-17 17:40:25.004 INFO   ControllerDiscovery  Start Discovering devices using identifier {"shortDiscriminator":4} ...
2024-07-17 17:40:25.121 INFO   ControllerDiscovery  Found 1 devices using identifier {"shortDiscriminator":4}
2024-07-17 17:40:25.121 INFO   MatterController     Commissioning device SII: undefined SAI: undefined SAT: undefined T: undefined DT: undefined PH: undefined ICD: undefined VP: 5120+1004 DN: undefined RI: undefined PI: undefined
2024-07-17 17:40:25.620 INFO   NobleBleClient       Peripheral  is not connectable ... ignoring
2024-07-17 17:40:26.515 INFO   BleChannel           Received Matter handshake response: 656c04f40005.
2024-07-17 17:40:28.252 INFO   PaseClient           Pase client: Paired successfully with ble://.
2024-07-17 17:40:28.253 INFO   SessionManager       End insecure session insecure/1717871622001245976
2024-07-17 17:40:28.254 INFO   Controller~missioner Executing commissioning step 0.1: GetInitialData
2024-07-17 17:40:28.944 INFO   Controller~missioner Executing commissioning step 3.1: GeneralCommissioning.ArmFailsafe
2024-07-17 17:40:29.063 INFO   Controller~missioner Executing commissioning step 5.1: GeneralCommissioning.ConfigureRegulatoryInformation
2024-07-17 17:40:29.243 INFO   Controller~missioner Executing commissioning step 5.2: TimeSynchronization.SynchronizeTime
2024-07-17 17:40:29.244 INFO   Controller~missioner Executing commissioning step 6.1: OperationalCredentials.DeviceAttestation
2024-07-17 17:40:30.114 INFO   Controller~missioner Executing commissioning step 7.1: OperationalCredentials.Certificates
2024-07-17 17:40:32.844 INFO   Controller~missioner Executing commissioning step 10.1: AccessControl
2024-07-17 17:40:32.845 INFO   Controller~missioner Executing commissioning step 11.1: NetworkCommissioning.Validate
2024-07-17 17:40:32.845 INFO   Controller~missioner Executing commissioning step 11.2: NetworkCommissioning.Wifi
2024-07-17 17:40:43.163 INFO   Controller~missioner Executing commissioning step 12.1: Reconnect
2024-07-17 17:40:46.613 INFO   CaseClient           Case client: Paired successfully with udp://fe80::3a73:eaff:fee3:b3df%en0:5540 and parameters idleIntervalMs: 500 activeIntervalMs: 300 activeThresholdMs: 4000 dataModelRevision: 17 interactionModelRevision: 11 specificationVersion: 0 maxPathsPerInvoke: 1
2024-07-17 17:40:46.629 INFO   SessionManager       End insecure session insecure/15683961764320135111
2024-07-17 17:40:46.638 INFO   Controller~missioner Executing commissioning step 15.1: GeneralCommissioning.Complete
2024-07-17 17:40:47.677 INFO   InteractionClient    Subscription successfully initialized with ID 4115941379 and maxInterval 60s.
2024-07-17 17:40:47.679 INFO   ClusterHelper        Unknown cluster 0x5 requested: UnknownCluster instance added.
2024-07-17 17:40:47.687 INFO   ClusterClient        Added unknown attribute 0x0 to cluster 0x5
2024-07-17 17:40:47.687 INFO   ClusterClient        Added unknown attribute 0x1 to cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Added unknown attribute 0x2 to cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Added unknown attribute 0x3 to cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Added unknown attribute 0x4 to cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 0 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 1 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 2 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 3 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 4 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 5 at cluster 0x5
2024-07-17 17:40:47.688 INFO   ClusterClient        Ignoring unknown command 6 at cluster 0x5
stateInformationCallback Node 333 connected
Commissioned Node: 333n
[ { deviceType: 22, revision: 1 } ]
attributeChangedCallback 333: Attribute undefined/1/768/colorTemperatureMireds changed to 500
[
   4, 29, 31, 40, 42,
  48, 49, 51, 54, 60,
  62, 63
]
Smart Bulb
Done.
matter-node> 2024-07-17 17:40:47.823 INFO   ControllerDiscovery  Found 1 devices using identifier {"shortDiscriminator":4}

matter-node> commands onoff toggle 333 1
Command Toggle 333/1/6/2 invoked 
Done.
matter-node> attributeChangedCallback 333: Attribute undefined/1/5/Unknown (0x3) changed to false
attributeChangedCallback 333: Attribute undefined/1/6/onOff changed to true
attributeChangedCallback 333: Attribute undefined/1/6/globalSceneControl changed to true
attributeChangedCallback 333: Attribute undefined/1/6/offWaitTime changed to 0
attributeChangedCallback 333: Attribute undefined/1/8/currentLevel changed to 1
attributeChangedCallback 333: Attribute undefined/1/5/Unknown (0x3) changed to false
attributeChangedCallback 333: Attribute undefined/1/8/currentLevel changed to 254
attributeChangedCallback 333: Attribute undefined/1/8/remainingTime changed to 0

matter-node> commands onoff toggle 333 1
Command Toggle 333/1/6/2 invoked 
Done.
matter-node> attributeChangedCallback 333: Attribute undefined/1/5/Unknown (0x3) changed to false
attributeChangedCallback 333: Attribute undefined/1/6/globalSceneControl changed to true
attributeChangedCallback 333: Attribute undefined/1/6/onTime changed to 0
attributeChangedCallback 333: Attribute undefined/1/5/Unknown (0x3) changed to false
attributeChangedCallback 333: Attribute undefined/1/6/onOff changed to false
attributeChangedCallback 333: Attribute undefined/1/6/onTime changed to 0
attributeChangedCallback 333: Attribute undefined/1/8/currentLevel changed to 254
attributeChangedCallback 333: Attribute undefined/1/8/remainingTime changed to 0

matter-node> nodes disconnect 333
stateInformationCallback Node 333 disconnected
2024-07-17 17:41:56.736 INFO   SessionManager       End CASE session secure/23584
2024-07-17 17:41:56.737 INFO   Commission~ontroller Session for peer node 333 disconnected ...
2024-07-17 17:41:56.737 INFO   PairedNode           Node 333: Session disconnected
Done.
matter-node> nodes connect 333
Done.
matter-node> commands onoff toggle 333 1
ERROR: Could not invoke command Toggle : Error: The exchange channel is closed. Please connect the device first.
Done.
matter-node> 
matter-node> 2024-07-17 17:42:31.685 ERROR  ExchangeManager      Cannot find a session for ID 23584
    at ExchangeManager.onMessage (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:182:19)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:107:26)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/net/UdpInterface.ts:34:13)
    at Socket.messageListener (/Users/hemiao/matter/matter.js/packages/matter-node.js/src/net/UdpChannelNode.ts:112:13)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:943:8)
2024-07-17 17:42:32.283 ERROR  ExchangeManager      Cannot find a session for ID 23584
    at ExchangeManager.onMessage (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:182:19)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:107:26)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/net/UdpInterface.ts:34:13)
    at Socket.messageListener (/Users/hemiao/matter/matter.js/packages/matter-node.js/src/net/UdpChannelNode.ts:112:13)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:943:8)
2024-07-17 17:42:32.858 ERROR  ExchangeManager      Cannot find a session for ID 23584
    at ExchangeManager.onMessage (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:182:19)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:107:26)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/net/UdpInterface.ts:34:13)
    at Socket.messageListener (/Users/hemiao/matter/matter.js/packages/matter-node.js/src/net/UdpChannelNode.ts:112:13)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:943:8)
2024-07-17 17:42:33.781 ERROR  ExchangeManager      Cannot find a session for ID 23584
    at ExchangeManager.onMessage (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:182:19)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:107:26)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/net/UdpInterface.ts:34:13)
    at Socket.messageListener (/Users/hemiao/matter/matter.js/packages/matter-node.js/src/net/UdpChannelNode.ts:112:13)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:943:8)
2024-07-17 17:42:35.345 ERROR  ExchangeManager      Cannot find a session for ID 23584
    at ExchangeManager.onMessage (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:182:19)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:107:26)
    at <anonymous> (/Users/hemiao/matter/matter.js/packages/matter.js/src/net/UdpInterface.ts:34:13)
    at Socket.messageListener (/Users/hemiao/matter/matter.js/packages/matter-node.js/src/net/UdpChannelNode.ts:112:13)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:943:8)

matter-node> 
matter-node> 
```

Below are the steps I've taken:

1. Device Pairing: Initiated the device pairing using the command `commission pair --ble --pairingCode 1032-742-2419 --node-id 333`.
2. Device control: Successfully toggled the device's on/off state with the command  `commands onoff toggle 333 1`.
3. Disconnect: Executed the `nodes disconnect 333` command to disconnect.
4. Reconnect: Re-established connection using the `nodes connect 333` command.
5. Device control: Tried to toggle the device's on/off state again with the `commands onoff toggle 333 1` command, command, but the attempt failed.

PS: After restarting the shell and reconnecting, I managed to control the device successfully.

Could anyone shed some light on what might have caused this? Has anyone experienced a similar issue? Thank you!

Development environment:

- Apple M1 Max
- macOS Sonoma 14.5
- Node.js 20.15.1
- npm 10.8.2
- code version: 0.10.0-alpha.0-20240716-446c872f

**Comment by Apollon77** [comment]
Thank you, it seems that the disconnection is not correctly remembered internally. I will look into this.

**Comment by Apollon77** [comment]
fix is in merged PR .. should come into next nightly .. so in 10h+ or such please try again :-)
