### ISSUE TITLE
Use matter-controller connect matter fail.

### ISSUE THREAD

**Issue by Firesuiry** [project-chip/matter.js#103]
I run

```npm run matter```

and I get
```
> @project-chip/matter-node.js@0.0.11 matter
> ts-node --project tsconfig.dist.json src/Device.ts

2023-04-20 20:17:09.306 INFO Device node-matter
2023-04-20 20:17:09.338 DEBUG MdnsBroadcaster announce commissioning mode 1 Matter test device 257 [object Object] 32768 3840
2023-04-20 20:17:09.341 INFO Device Listening
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▄▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▀▄▀▄█ █   █ █
█ █▄▄▄█ ██ ▀▀▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄▄▄▄▄▄▄█
█▄ ▄█▄ ▄▄ ▀ █  ▄▀██ █▀█
██ █▀▀ ▄▄█ █ ▀▄▄██ ▀█▀█
█▄▄████▄▄▄▀▄▀ ▀██▄▄▀▄▀█
█ ▄▄▄▄▄ █  ▄█▄█▄▄█▄ █ █
█ █   █ █▄▀▀█▄ ▄▀▀▄ ▀██
█ █▄▄▄█ █  ▀█▄█ ▀█  ▀ █
█▄▄▄▄▄▄▄█▄█▄█▄██▄██▄█▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

QR Code URL: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT:Y.K90AFN00KA0648G00
Manual pairing code: 34970112332
2023-04-20 20:17:09.344 DEBUG UdpChannelNode initialize multicast interface 172.16.6.139 udp4 5353 enp9s0
2023-04-20 20:17:09.344 DEBUG UdpChannelNode initialize multicast interface ::%enp9s0 udp6 5353 enp9s0
```

then I open another shell and run
```
npm run matter-controller -- -ip 172.16.6.139
```
but I get
```
> @project-chip/matter-node.js@0.0.11 matter-controller
> ts-node --project tsconfig.dist.json src/Controller.ts -ip 172.16.6.139

2023-04-20 20:25:28.927 INFO Controller node-matter
2023-04-20 20:25:28.953 DEBUG MessageExchange new MessageExchange 0 13333 300 5000 5
2023-04-20 20:25:28.954 DEBUG ExchangeManager sending id:0/13333/2895701458 t:0/32 reqAck:true payload: 153001207f734f35a54970d731b73b52eb029a74b8c546d1f2f97e0b46244495e0f411cc25021c6f240300280418
2023-04-20 20:25:28.956 DEBUG MessageExchange new MessageExchange 0 13333 300 5000 5
2023-04-20 20:25:28.957 DEBUG MessageExchange onMessageReceived 0 id:0/13333/2895701458 t:0/32 reqAck:true payload: 153001207f734f35a54970d731b73b52eb029a74b8c546d1f2f97e0b46244495e0f411cc25021c6f240300280418
2023-04-20 20:25:28.957 ERROR ExchangeManager Error: Unsupported protocol 0
    at ExchangeManager.<anonymous> (/home/yinsy/esp/matter.js/packages/matter-node.js/src/matter/common/ExchangeManager.ts:104:54)
    at Generator.next (<anonymous>)
    at fulfilled (/home/yinsy/esp/matter.js/packages/matter-node.js/src/matter/common/ExchangeManager.ts:10:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-20 20:25:29.298 DEBUG MessageExchange Resubmit message 2895701458 (attempt 1, next backoff time 392ms))
2023-04-20 20:25:29.298 DEBUG ExchangeManager sending id:0/13333/2895701458 t:0/32 reqAck:true payload: 153001207f734f35a54970d731b73b52eb029a74b8c546d1f2f97e0b46244495e0f411cc25021c6f240300280418
2023-04-20 20:25:29.299 DEBUG MessageExchange onMessageReceived 0 id:0/13333/2895701458 t:0/32 reqAck:true payload: 153001207f734f35a54970d731b73b52eb029a74b8c546d1f2f97e0b46244495e0f411cc25021c6f240300280418
2023-04-20 20:25:29.300 DEBUG ExchangeManager sending id:0/13333/2895701459 t:0/16 acked:2895701458 reqAck:false payload: 
2023-04-20 20:25:29.301 DEBUG MessageExchange onMessageReceived 0 id:0/13333/2895701459 t:0/16 acked:2895701458 reqAck:false payload:
```

it seems not success, is there any wrong operation? how can I solve this?

**Comment by Apollon77** [comment]
Hi, it is not working tohave controller and device to run on the same host as of now. The reason is that when you have two processes listens for UDP *cast messages only one process will receive them as you can see in the logs. This breaks it. You  need to use two different "network hosts" for this usecase. We could add this maybe to the readme

**Comment by Firesuiry** [comment]
> 您好，目前无法让控制器和设备在同一主机上运行。原因是当您有两个进程侦听 UDP *cast 消息时，只有一个进程会收到它们，正如您在日志中看到的那样。这打破了它。您需要为此用例使用两个不同的“网络主机”。我们可以将其添加到自述文件中

thank you for your reply~
