### ISSUE TITLE
Troubleshooting Gateway Device Configuration Error

### ISSUE THREAD

**Issue by joehecn** [project-chip/matter.js#1048]
I encountered an error while configuring a gateway device, with the following error message:

```bash
2024-07-23 19:29:34.962 INFO   ClusterClient        Added unknown attribute 0x125d0007 to cluster 0x31
Error happened during command: Error: Event accessControlEntryChanged needs to be supported by cluster AccessControl (31)
Error: Event accessControlEntryChanged needs to be supported by cluster AccessControl (31)
    at ClusterServer (/Users/hemiao/matter/matter.js/packages/matter.js/src/cluster/server/ClusterServer.ts:419:19)
    at PairedNode.createDevice (/Users/hemiao/matter/matter.js/packages/matter.js/src/device/PairedNode.ts:569:17)
    at PairedNode.initializeEndpointStructure (/Users/hemiao/matter/matter.js/packages/matter.js/src/device/PairedNode.ts:450:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PairedNode.initialize (/Users/hemiao/matter/matter.js/packages/matter.js/src/device/PairedNode.ts:254:13)
    at Function.create (/Users/hemiao/matter/matter.js/packages/matter.js/src/device/PairedNode.ts:162:9)
    at CommissioningController.connectNode (/Users/hemiao/matter/matter.js/packages/matter.js/src/CommissioningController.ts:350:28)
    at CommissioningController.commissionNode (/Users/hemiao/matter/matter.js/packages/matter.js/src/CommissioningController.ts:267:13)
    at Object.handler (/Users/hemiao/matter/matter.js/packages/matter-node-shell.js/src/shell/cmd_commission.ts:127:41)
```

 What is the cause of this error? 
How can it be resolved? 

Thank you for your help!

For more details, please see the attachment:

[console.txt](https://github.com/user-attachments/files/16348030/console.txt)
[log.txt](https://github.com/user-attachments/files/16348031/log.txt)
![image](https://github.com/user-attachments/assets/274241ae-759d-4048-ac57-513b5c61de05)

**Comment by Apollon77** [comment]
Yeeaayyy ... seems the devcie is not really compliant because it does not support mandatory events ... need to look into this

**Comment by Apollon77** [comment]
The linked PR should ignore such errornous defined clusters for now. After merge please retest and tell the result and ideally please add an updated full commissioning log. Thank you

**Comment by joehecn** [comment]
After updating the version, the device has successfully connected to the network. 
I will continue testing the device's control functions. 
Thank you very much for your help; great job!

[console.txt](https://github.com/user-attachments/files/16357400/console.txt)
[log.txt](https://github.com/user-attachments/files/16357401/log.txt)

**Comment by Apollon77** [comment]
Cool and thank you for the information

**Comment by Apollon77** [comment]
@joehecn can you please tell/show a bit more on which devices you have paired to the bridge? Because some things are strange and we try to reproduce that. Thanks.
