### ISSUE TITLE
Update cluster features in storage/consider only current and not stored features

### ISSUE THREAD

**Issue by jpadie** [project-chip/matter.js#1161]
Suggestion that conformance errors are not automatically fatal errors in all cases.  As an example use case:

set an onoff lighting device with colour support and colour temperature support and provide defaults for the mandatory attributes.
then remove colour temperature support.

the deployment will fail for conformance because an attribute is in the device storage that is contrary to the conformance requirements.  But this could be silently ignored instead of resulting in a fatal error.

**Comment by Apollon77** [comment]
The issue is more that the storage contains meta data about features/clusters that are removed in the meantime ... so we need to see how we might support this.
Formally adding and removing clusters and features and attributes and commands should be possible - especially in a bridge

**Comment by Apollon77** [comment]
if you do a "set" with an unconformant value then you will get an exception. Catch them and you can filter themnm most likely by the Error instance (ValidationError).

**Comment by t0bst4r** [comment]
+1

Having the same errors when building devices for my home assistant integration. When I removed color temperature for some devices, affected users reported the same issue: 

color temperature is set from storage even if the feature is not activated anymore.

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 5cd61e4a2f9144a4817d9b2ed319c0fd.aggregator.light_wled.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 5cd61e4a2f9144a4817d9b2ed319c0fd.aggregator.light_wled.colorControl.state.colorTemperatureMireds: Conformance "CT": Matter does not allow you to set this attribute (128)
        at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:305:13)
        at Object.colorTemperatureMireds (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:41:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23)
```
