### ISSUE TITLE
PowerSource

### ISSUE THREAD

**Issue by rcaceiro** [project-chip/matter.js#1339]
Hi, I am trying to set battery info into the endpoint, I receive always an error in runtime something like this
```
Behaviors have errors
 Cause #0: Error initializing 1730302582525.humidity.powerSource
```

I leave the code based on a example of ours

```
#!/usr/bin/env node
/**
 * @license
 * Copyright 2022-2024 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * This example shows how to create a simple Sensor Matter device as temperature or humidity device.
 * It can be used as CLI script and starting point for your own device node implementation.
 * This example is CJS conform and do not use top level await's.
 */

import {Endpoint, EndpointServer, Environment, ServerNode, StorageService, Time} from "@matter/main";
import {HumiditySensorDevice} from "@matter/main/devices/humidity-sensor";
import {TemperatureSensorDevice} from "@matter/main/devices/temperature-sensor";
import {logEndpoint} from "@matter/main/protocol";
import {DeviceTypeId, VendorId} from "@matter/main/types";
import {PowerSourceServer} from "@matter/main/behaviors";
import {PowerSource} from "@matter/main/clusters";

async function main() {
    /** Initialize configuration values */
    const {
        isTemperature,
        interval,
        deviceName,
        vendorName,
        passcode,
        discriminator,
        vendorId,
        productName,
        productId,
        port,
        uniqueId,
    } = await getConfiguration();

    /**
     * Create a Matter ServerNode, which contains the Root Endpoint and all relevant data and configuration
     */
    const server = await ServerNode.create({
        // Required: Give the Node a unique ID which is used to store the state of this node
        id: uniqueId,

        // Provide Network relevant configuration like the port
        // Optional when operating only one device on a host, Default port is 5540
        network: {
            port,
        },

        // Provide Commissioning relevant settings
        // Optional for development/testing purposes
        commissioning: {
            passcode,
            discriminator,
        },

        // Provide Node announcement settings
        // Optional: If Ommitted some development defaults are used
        productDescription: {
            name: deviceName,
            deviceType: DeviceTypeId(
                isTemperature ? TemperatureSensorDevice.deviceType : HumiditySensorDevice.deviceType,
            ),
        },

        // Provide defaults for the BasicInformation cluster on the Root endpoint
        // Optional: If Omitted some development defaults are used
        basicInformation: {
            vendorName,
            vendorId: VendorId(vendorId),
            nodeLabel: productName,
            productName,
            productLabel: productName,
            productId,
            serialNumber: `matterjs-${uniqueId}`,
            uniqueId,
        },
    });

    /**
     * Matter Nodes are a composition of endpoints. Create and add a single endpoint to the node. This example uses the
     * OnOffLightDevice or OnOffPlugInUnitDevice depending on the value of the type parameter. It also assigns this Part a
     * unique ID to store the endpoint number for it in the storage to restore the device on restart.
     * In this case we directly use the default command implementation from matter.js. Check out the DeviceNodeFull example
     * to see how to customize the command handlers.
     */
    const sensor = HumiditySensorDevice
        .with(PowerSourceServer.with(PowerSource.Feature.Battery, PowerSource.Feature.Replaceable))
    const endpoint = new Endpoint(sensor, {
        id: `humidity`,
        relativeHumidityMeasurement: {
            measuredValue: 5000,
        },
        powerSource: {
            batChargeLevel: PowerSource.BatChargeLevel.Ok,
            batReplaceability: PowerSource.BatReplaceability.UserReplaceable,
            batCommonDesignation: PowerSource.BatCommonDesignation.Aa,
            batApprovedChemistry: PowerSource.BatApprovedChemistry.Alkaline,
            status: PowerSource.PowerSourceStatus.Active,
        }
    })
    await server.add(endpoint);

    /**
     * Log the endpoint structure for debugging reasons and to allow to verify anything is correct
     */
    logEndpoint(EndpointServer.forEndpoint(server));

    /**
     * In order to start the node and announce it into the network we use the run method which resolves when the node goes
     * offline again because we do not need anything more here. See the Full example for other starting options.
     * The QR Code is printed automatically.
     */
    await server.run();
}

main().catch(error => console.error(error));

/*********************************************************************************************************
 * Convenience Methods
 *********************************************************************************************************/

async function getConfiguration() {
    /**
     * Collect all needed data
     *
     * This block collects all needed data from cli, environment or storage. Replace this with where ever your data come from.
     *
     * Note: This example uses the matter.js process storage system to store the device parameter data for convenience
     * and easy reuse. When you also do that be careful to not overlap with Matter-Server own storage contexts
     * (so maybe better not do it ;-)).
     */
    const environment = Environment.default;

    const storageService = environment.get(StorageService);
    console.log(`Storage location: ${storageService.location} (Directory)`);
    console.log(
        'Use the parameter "--storage-path=NAME-OR-PATH" to specify a different storage location in this directory, use --storage-clear to start with an empty storage.',
    );
    const deviceStorage = (await storageService.open("device")).createContext("data");

    const isTemperature = await deviceStorage.get("isTemperature", environment.vars.get("type") !== "humidity");
    if (await deviceStorage.has("isTemperature")) {
        console.log(
            `Device type ${isTemperature ? "temperature" : "humidity"} found in storage. --type parameter is ignored.`,
        );
    }
    let interval = environment.vars.number("interval") ?? (await deviceStorage.get("interval", 60));
    if (interval < 1) {
        console.log(`Invalid Interval ${interval}, set to 60s`);
        interval = 60;
    }

    const deviceName = "Matter test device";
    const vendorName = "matter-node.js";
    const passcode = environment.vars.number("passcode") ?? (await deviceStorage.get("passcode", 20202021));
    const discriminator = environment.vars.number("discriminator") ?? (await deviceStorage.get("discriminator", 3840));
    // product name / id and vendor id should match what is in the device certificate
    const vendorId = environment.vars.number("vendorid") ?? (await deviceStorage.get("vendorid", 0xfff1));
    const productName = `node-matter OnOff ${isTemperature ? "Temperature" : "Humidity"}`;
    const productId = environment.vars.number("productid") ?? (await deviceStorage.get("productid", 0x8000));

    const port = environment.vars.number("port") ?? 5540;

    const uniqueId =
        environment.vars.string("uniqueid") ?? (await deviceStorage.get("uniqueid", Time.nowMs().toString()));

    // Persist basic data to keep them also on restart
    await deviceStorage.set({
        passcode,
        discriminator,
        vendorid: vendorId,
        productid: productId,
        interval,
        isTemperature,
        uniqueid: uniqueId,
    });

    return {
        isTemperature,
        interval,
        deviceName,
        vendorName,
        passcode,
        discriminator,
        vendorId,
        productName,
        productId,
        port,
        uniqueId,
    };
}
```

**Comment by rcaceiro** [comment]
Hello, this is the stack that node prints,

```
2024-10-31 08:04:14.212 INFO   ServerNodeStore      Opened 1730302582525 storage at /home/rcaceiro/.matter/1730302582525
2024-10-31 08:04:14.230 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.basicInformation.state
2024-10-31 08:04:14.230 WARN   BasicInfor~ionServer Using development values for some BasicInformation attributes: hardwareVersion: 0 softwareVersion: 0
2024-10-31 08:04:14.246 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.accessControl.state
2024-10-31 08:04:14.255 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.groupKeyManagement.state
2024-10-31 08:04:14.263 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.generalCommissioning.state
2024-10-31 08:04:14.268 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.administratorCommissioning.state
2024-10-31 08:04:14.278 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.operationalCredentials.state
2024-10-31 08:04:14.294 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.generalDiagnostics.state
2024-10-31 08:04:14.308 DEBUG  Transaction          Transaction initialize<1730302582525>#1 locked 1730302582525.descriptor.state
2024-10-31 08:04:14.310 DEBUG  EventHandler         Set/Restore last event number: 0
2024-10-31 08:04:14.311 DEBUG  Transaction          Transaction initialize<1730302582525>#1 committed and unlocked 8 resources
2024-10-31 08:04:14.312 INFO   Endpoint             1730302582525 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions 💤controller ✔descriptor
2024-10-31 08:04:14.312 DEBUG  Transaction          Transaction reactor<1730302582525.commissioning.#initializeNode>#5 locked 1730302582525.commissioning.state
2024-10-31 08:04:14.312 DEBUG  Transaction          Transaction reactor<1730302582525.commissioning.#initializeNode>#5 committed and unlocked 1 resource
2024-10-31 08:04:14.331 DEBUG  Transaction          Transaction initialize<1730302582525.humidity>#9 locked 1730302582525.humidity.identify.state
2024-10-31 08:04:14.336 DEBUG  Transaction          Transaction initialize<1730302582525.humidity>#9 locked 1730302582525.humidity.relativeHumidityMeasurement.state
2024-10-31 08:04:14.353 DEBUG  Transaction          Transaction initialize<1730302582525.humidity>#9 locked 1730302582525.humidity.descriptor.state
2024-10-31 08:04:14.353 DEBUG  Transaction          Transaction reactor<1730302582525.descriptor.#updatePartsList>#a locked 1730302582525.descriptor.state
2024-10-31 08:04:14.353 DEBUG  Transaction          Transaction reactor<1730302582525.descriptor.#updatePartsList>#a committed and unlocked 1 resource
2024-10-31 08:04:14.354 ERROR  Transaction          Rolling back initialize<1730302582525.humidity>#9 due to error: Behaviors have errors
2024-10-31 08:04:14.354 DEBUG  Transaction          Transaction initialize<1730302582525.humidity>#9 rolled back and unlocked 3 resources
Behaviors have errors
      at /home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:171:27
      at all (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:699:25)
      at /home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:689:17
      Cause #0: Error initializing 1730302582525.humidity.powerSource
        at crash (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:66:19)
        at ClusterServerBacking.[construct] (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:80:13)
        at initializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:275:80)
        at invokeInitializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:572:30)
        at AsyncConstruction.start (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:276:17)
        at Behaviors.#createBacking (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:534:30)
        at Behaviors.activate (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:325:28)
        at initializeBehaviors (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:159:26)
        at actOffline (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/context/server/OfflineContext.ts:48:20)
        at Transaction.act (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/state/transaction/Tx.ts:98:29)
      Caused by: Synchronous access to 1730302582525.humidity.descriptor is impossible because it is still initializing
        at Behaviors.createSync (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:248:19)
        at HumiditySensorAgent.get (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/endpoint/Agent.ts:83:49)
        at PowerSourceServer.initialize (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behaviors/power-source/PowerSourceServer.ts:15:20)
        at ClusterServerBacking.invokeInitializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:116:25)
        at ClusterServerBacking.invokeInitializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/ServerBehaviorBacking.ts:40:31)
        at ClusterServerBacking.invokeInitializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/ClusterServerBacking.ts:82:30)
        at ClusterServerBacking.[construct] (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:75:34)
        at initializer (/home/rcaceiro/WebstormProjects/matter/node_modules/@matter/general/src/util/Construction.ts:275:80)
        (see parent frames)
```

I was checking every field to fill in and the problem persists, probably I am using it wrong, I don't know, I tryied the batChargeLevel in 2 ways but the same out come
```
        powerSource: {
            activeBatFaults: [],
            batApprovedChemistry: PowerSource.BatApprovedChemistry.Alkaline,
            batChargeLevel: 69,
            // batChargeLevel: PowerSource.BatChargeLevel.Ok,
            batCommonDesignation: PowerSource.BatCommonDesignation.Aa,
            batPresent: true,
            batReplaceability: PowerSource.BatReplaceability.UserReplaceable,
            batReplacementNeeded: false,
            batTimeRemaining: 12,
            batVoltage: 312,
            description: "Primary Battery",
            endpointList: [],
            order: 0,
            status: PowerSource.PowerSourceStatus.Active,
        }
```

**Comment by Apollon77** [comment]
Good catch, we will prepare a fix
