### ISSUE TITLE
[macOS] Commissioning failure in matter-controller example at 'step 12.1: Reconnect'

### ISSUE THREAD

**Issue by leonardocavagnis** [project-chip/matter.js#1363]
I'm testing the `matter-controller` example, and I'm encountering an issue during the commissioning phase at the Reconnect step.

```
...
2024-11-05 14:42:05.841 INFO   Controller~missioner Executing commissioning step 12.1: Reconnect
2024-11-05 14:42:05.841 DEBUG  Controller~missioner Reconnecting with device ...
2024-11-05 14:42:05.841 DEBUG  BtpSessionHandler    Closing BTP session
2024-11-05 14:42:05.842 DEBUG  BleChannel           Disconnected from peripheral
2024-11-05 14:42:05.844 DEBUG  MdnsScanner          Registered waiter for query 5B37AA2D63C5A0B5-03D2FC63DD6519AA._matter._tcp.local with timeout 120 seconds
2024-11-05 14:42:05.844 DEBUG  MdnsScanner          Set 1 query records for query 5B37AA2D63C5A0B5-03D2FC63DD6519AA._matter._tcp.local: [{"name":"5B37AA2D63C5A0B5-03D2FC63DD6519AA._matter._tcp.local","recordClass":1,"recordType":33}]
2024-11-05 14:42:05.845 DEBUG  MdnsScanner          Sending 3 query records for 2 queries with 0 known answers. Re-Announce in 1.5 seconds
2024-11-05 14:42:07.346 DEBUG  MdnsScanner          Sending 3 query records for 2 queries with 0 known answers. Re-Announce in 3 seconds
2024-11-05 14:42:10.348 DEBUG  MdnsScanner          Sending 3 query records for 2 queries with 0 known answers. Re-Announce in 6 seconds
2024-11-05 14:42:15.049 DEBUG  MdnsScanner          Finishing waiter for query _S15._sub._matterc._udp.local, resolving: true
2024-11-05 14:42:15.050 DEBUG  MdnsScanner          Removing query _S15._sub._matterc._udp.local
2024-11-05 14:42:15.050 INFO   ControllerDiscovery  Found 0 devices using identifier {"shortDiscriminator":15}
2024-11-05 14:42:16.349 DEBUG  MdnsScanner          Sending 1 query records for 1 queries with 0 known answers. Re-Announce in 12 seconds
2024-11-05 14:42:28.350 DEBUG  MdnsScanner          Sending 1 query records for 1 queries with 0 known answers. Re-Announce in 24 seconds
2024-11-05 14:42:52.352 DEBUG  MdnsScanner          Sending 1 query records for 1 queries with 0 known answers. Re-Announce in 48 seconds
2024-11-05 14:43:40.354 DEBUG  MdnsScanner          Sending 1 query records for 1 queries with 0 known answers. Re-Announce in 96 seconds
2024-11-05 14:44:05.845 DEBUG  MdnsScanner          Finishing waiter for query 5B37AA2D63C5A0B5-03D2FC63DD6519AA._matter._tcp.local, resolving: true
2024-11-05 14:44:05.846 DEBUG  MdnsScanner          Removing last query 5B37AA2D63C5A0B5-03D2FC63DD6519AA._matter._tcp.local and stopping announce timer
2024-11-05 14:44:05.847 ERROR  Controller           The operational device cannot be found on the network. Please make sure it is online.
  at Function.discoverOperationalDevice (/Users/leonardocavagnis/Desktop/matter.js/packages/protocol/src/peer/ControllerDiscovery.ts:127:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async <anonymous> (/Users/leonardocavagnis/Desktop/matter.js/packages/protocol/src/peer/PeerSet.ts:517:32)

```

**My setup:**

- Open Thread Border Router based on ESP32 device
- Arduino Nano Matter (a Matter device with BLE and Thread implementing an OnOff cluster)
- macOS Sequoia 15.1 (MacBook Pro 2023 - Apple M2 Pro)

**To reproduce:**

```
sudo npm run matter-controller --
--ble 
--ble-thread-networkname=<my-ble-threadnetworkname> 
--ble-thread-operationaldataset=<my-ble-thread-operationalset>
--pairingcode=<my-pairing-code>
```

**Complete output log:**
[matter-js-output-log-reconnect-issue.txt](https://github.com/user-attachments/files/17633573/matter-js-output-log-reconnect-issue.txt)

**Comment by Apollon77** [comment]
That an MDNS issue now where seems your host is not receiving the MDNS operational announcement. Question ... why ...

In Linux when it is a Thread device you need to tweak things - see https://github.com/project-chip/matter.js/blob/main/docs/TROUBLESHOOTING.md#ipv6-linux-system-details ... for me interestingly it works with an own VM based OTBR ... no ideal if there is something comparable that needs to be tweak that the RA and RIO are correctly received?

**Comment by leonardocavagnis** [comment]
@Apollon77 thanks for suggestions!

Everything seems work fine. Any other ideas?

**From ESP32 OTBR Serial log:**
```
I (486) wifi:wifi driver task: 3fcb4700, prio:23, stack:6144, coI (2996) wifi:new:<12,0>, old:<1,0>, ap:<255,255>, sta:<12,0>, prof:1
I (3466) wifi:state: init -> auth (b0)
I (3466) wifi:state: auth -> assoc (0)
I (3476) wifi:state: assoc -> run (10)
I (3496) wifi:connected with <my-ssid-network>, aid = 1, channel 12, BW20, bssid = 80:16:05:4b:b7:01
I (3496) wifi:security: WPA2-PSK, phy: bgn, rssi: -68
I (3496) wifi:pm start, type: 1

I (3496) wifi:set rx beacon pti, rx_bcn_pti: 0, bcn_timeout: 25000, mt_pti: 0, mt_time: 10000
I (3556) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (3666) wifi:<ba-add>idx:0 (ifx:0, 80:16:05:4b:b7:01), tid:0, ssn:0, winSize:64
[0;32mI (5476) example_connect: Got IPv6 event: Interface "example_netif_sta" address: fe80:0000:0000:0000:764d:bdff:fea1:b4e8, type: ESP_IP6_ADDR_IS_LINK_LOCAL[0m
[0;32mI (6496) esp_netif_handlers: example_netif_sta ip: 192.168.1.11, mask: 255.255.255.0, gw: 192.168.1.1[0m
[0;32mI (6496) example_connect: Got IPv4 event: Interface "example_netif_sta" address: 192.168.1.11[0m
[0;32mI (6496) example_common: Connected to example_netif_sta[0m
[0;32mI (6496) example_common: - IPv4 address: 192.168.1.11,[0m
[0;32mI (6496) example_common: - IPv6 address: fe80:0000:0000:0000:764d:bdff:fea1:b4e8, type: ESP_IP6_ADDR_IS_LINK_LOCAL[0m
[0;32mI (6496) example_common: - IPv6 address: fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, type: ESP_IP6_ADDR_IS_UNIQUE_LOCAL[0m
```
**On my mac:**
```
 ~ % ndp -a | grep en0                            
fdc7:87f4:6f59:1ea0:1c6f:a38d:8104:d859 a6:5d:49:a7:24:a2    en0 permanent R      
fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8 74:4d:bd:a1:b4:e8    en0 17s       R      
fdde:ad00:beef:cafe:da:13d9:5048:fa54   a6:5d:49:a7:24:a2    en0 permanent R      
fe80::1%en0                             (incomplete)         en0 expired   N      
macbook-pro-di-leo.local                a6:5d:49:a7:24:a2    en0 permanent R      
fe80::37ff:8031:a777:e43%en0            dc:e5:5b:63:b2:73    en0 14h33m38s S  R   
fe80::764d:bdff:fea1:b4e8%en0           (incomplete)         en0 expired   N      
fe80::8216:5ff:fe4b:b700%en0            80:16:5:4b:b7:0      en0 14h33m24s S  R 

~ % ping6 fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8  
PING6(56=40+8+8 bytes) fdc7:87f4:6f59:1ea0:1c6f:a38d:8104:d859 --> fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8
16 bytes from fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, icmp_seq=0 hlim=255 time=21.787 ms
16 bytes from fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, icmp_seq=1 hlim=255 time=6.412 ms
16 bytes from fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, icmp_seq=2 hlim=255 time=7.466 ms
16 bytes from fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, icmp_seq=3 hlim=255 time=10.543 ms
16 bytes from fdc7:87f4:6f59:1ea0:764d:bdff:fea1:b4e8, icmp_seq=4 hlim=255 time=10.173 ms
...
```

**Comment by Apollon77** [comment]
Honestly ... I have no further idea right now beside checking with dns-sd or avahi on low level aside to check the the MDNS messages arrive on your mac. if not then this is the issue - then something is with the UDP "routing". If they arrive there bit are not seen by matter.js then we can look further there.

**Comment by leonardocavagnis** [comment]
> Honestly ... I have no further idea right now beside checking with dns-sd or avahi on low level aside to check the the MDNS messages arrive on your mac. if not then this is the issue - then something is with the UDP "routing". If they arrive there bit are not seen by matter.js then we can look further there.

Everything seems good also in this side.

```
~ % dns-sd -B _matter._tcp.
Browsing for _matter._tcp.
DATE: ---Thu 07 Nov 2024---
10:51:10.735  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:51:10.736  Add        3  15 local.               _matter._tcp.        5B37AA2D63C5A0B5-02FE3DC8E123A320
10:51:10.736  Add        3   1 local.               _matter._tcp.        5B37AA2D63C5A0B5-F924A25BF5CF86F9
10:51:10.736  Add        3  15 local.               _matter._tcp.        5B37AA2D63C5A0B5-F924A25BF5CF86F9
10:51:10.736  Add        3  23 local.               _matter._tcp.        5B37AA2D63C5A0B5-F924A25BF5CF86F9
10:51:10.736  Add        2  15 local.               _matter._tcp.        D4C7C8A2C4C1084C-00000000D5FA02D1
10:51:15.603  Add        2  15 local.               _matter._tcp.        5B37AA2D63C5A0B5-306EC820F139B82F
10:51:15.721  Add        2  23 local.               _matter._tcp.        5B37AA2D63C5A0B5-306EC820F139B82F
10:52:10.979  Add        2   1 local.               _matter._tcp.        5B37AA2D63C5A0B5-306EC820F139B82F
10:52:11.225  Add        2  15 local.               _matter._tcp.        5B37AA2D63C5A0B5-E6E359A1250710AD
```

**Comment by Apollon77** [comment]
Would be great to see this with an actual log ...  because the question is if the instance name that is expected to show up shows up. :-) In fact these are all your potential operative used matter devices ... so the question is if the new one shows up

**Comment by leonardocavagnis** [comment]
Ah wait! Great news... I disabled the firewall installed on my system, and everything works well!
Disabling the firewall is a drastic solution, though, so I’m trying to figure out which ports I need to enable to allow `matter.js` to work properly.

**Comment by Apollon77** [comment]
iinteresting ... in fact for MDNS it is 5353 when I know correctly ... try if this already works

**Comment by Apollon77** [comment]
PS: Is there anything you think makes sense to add to the readme?

**Comment by leonardocavagnis** [comment]
> PS: Is there anything you think makes sense to add to the readme?

I suggest adding this to the troubleshooting guide rather than the README. 
Something like: 

> _"If you experience connectivity issues (e.g., mDNS not working properly), check your firewall settings or network filters. Make sure to add exceptions for the Node.js application and/or the mDNS port (5353)."_

If you'd like, I can open a PR to include this information.

**Comment by Apollon77** [comment]
PR would be awesome. Thanks

**Comment by leonardocavagnis** [comment]
> PR would be awesome. Thanks

Done https://github.com/project-chip/matter.js/pull/1377 ;)
