### ISSUE TITLE
ModeTag validation uses wrong "ModeTags" instance

### ISSUE THREAD

**Issue by Apollon77** [project-chip/matter.js#1455]
This issue is the essence out of https://github.com/project-chip/matter.js/discussions/1444#discussioncomment-11412712

Repro use the attacked example file.

My findings are that two things are "wrong":
1.) In element ModeBase the datatype ModeTagStruct has a child "Value" which is as scraped an enum16 but do not have any children. It needs to be changed to type "ModeTag" to point to the "right" types

2.) When then a derived cluster (e.g. EvseMode) is used then the ValueValidator - when working on the attribute supportedModes and all "below that structure like then also  "ModeTag" type is use the definition of MopdBase, so all "derived overwritten types" are ignored because the validator iterated down the schema - and this schema is "ModeBase".
I also tried to "copy" all the datatypes and the relevant attribute to the EnergyEvseMode.ts element file for tests, but it was still not taking these "overwritten" things

Eample script
```javascript
import { Endpoint, ServerNode } from "@matter/main";
import { EnergyEvseModeServer } from "@matter/main/behaviors";
import { EnergyEvseMode } from "@matter/main/clusters";
import { OnOffPlugInUnitDevice } from "@matter/main/devices";

// Create the "node".  In Matter a "node" is a standalone device
const node = await ServerNode.create();

// Define the endpoint for the device.  This is the "thing/device" that will appear on the network.
const measuredSocketEndpoint = new Endpoint(OnOffPlugInUnitDevice.with(EnergyEvseModeServer), {
    id: "socket",

    energyEvseMode: {
        currentMode: EnergyEvseMode.ModeTag.Manual,
        startUpMode: EnergyEvseMode.ModeTag.Manual,
        supportedModes: [
            {
                label: "Manual",
                mode: 0,
                modeTags: [
                    {
                        value: EnergyEvseMode.ModeTag.Manual,
                    },
                ],
            },
            {
                label: "Quick",
                mode: 1,
                modeTags: [
                    {
                        value: EnergyEvseMode.ModeTag.TimeOfUse,
                    },
                ],
            },
        ],
    },
});

// Create the light "endpoint".  In Matter an "endpoint" is a component of a node
await node.add(measuredSocketEndpoint);

// Run our server
await node.start();
```

**Comment by Apollon77** [comment]
Exception is:

```
2024-11-29 12:10:15.033 DEBUG  Transaction          Transaction initialize<node0.socket>#9 locked node0.socket.descriptor.state
2024-11-29 12:10:15.033 DEBUG  Transaction          Transaction reactor<node0.descriptor.#updatePartsList>#a locked node0.descriptor.state
2024-11-29 12:10:15.033 DEBUG  Transaction          Transaction reactor<node0.descriptor.#updatePartsList>#a committed and unlocked 1 resource
2024-11-29 12:10:15.033 ERROR  Transaction          Rolling back initialize<node0.socket>#9 due to error: Behaviors have errors
2024-11-29 12:10:15.033 DEBUG  Transaction          Transaction initialize<node0.socket>#9 rolled back and unlocked 4 resources
2024-11-29 12:10:15.034 FATAL  Logger               Unhandled error detected: Behaviors have errors
  at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:128:21
  at all (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:375:17)
  at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:365:11
  Cause #0: Error initializing node0.socket.energyEvseMode
    at crash (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
    at [construct] (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/internal/BehaviorBacking.js:57:7)
    at initializeDeferred (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:61:73)
    at invokeInitializer (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:281:26)
    at AsyncConstruction.start (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:62:9)
    at #createBacking (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:413:26)
    at Behaviors.activate (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:242:36)
    at initializeBehaviors (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:119:16)
    at actOffline (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/context/server/OfflineContext.js:28:14)
    at Transaction.act (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/transaction/Tx.js:71:25)
  Caused by: Validating node0.socket.energyEvseMode.state.supportedModes.0.modeTags.0.value: Value "16384" is not defined in enum (135)
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:100:13
    at Object.value (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22)
    at validateStruct (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:192:23)
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22
    at validateEntries (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:235:11)
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:245:22
    at Object.modeTags (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22)
    at validateStruct (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:192:23)
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22
    at validateEntries (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:235:11)
file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:128
        (causes) => new EndpointBehaviorsError(causes)
                    ^

EndpointBehaviorsError [AggregateError]: Behaviors have errors
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:128:21
    at all (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:375:17)
    at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:365:11 {
  format: [Function: format],
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]],
  [errors]: [
    BehaviorInitializationError: Error initializing node0.socket.energyEvseMode
        at crash (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
        at [construct] (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/internal/BehaviorBacking.js:57:7)
        at initializeDeferred (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:61:73)
        at invokeInitializer (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:281:26)
        at AsyncConstruction.start (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/general/dist/esm/util/Construction.js:62:9)
        at #createBacking (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:413:26)
        at Behaviors.activate (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:242:36)
        at initializeBehaviors (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/endpoint/properties/Behaviors.js:119:16)
        at actOffline (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/context/server/OfflineContext.js:28:14)
        at Transaction.act (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/transaction/Tx.js:71:25) {
      cause: DatatypeError: Validating node0.socket.energyEvseMode.state.supportedModes.0.modeTags.0.value: Value "16384" is not defined in enum (135)
          at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:100:13
          at Object.value (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22)
          at validateStruct (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:192:23)
          at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22
          at validateEntries (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:235:11)
          at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:245:22
          at Object.modeTags (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22)
          at validateStruct (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:192:23)
          at file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/conformance.js:15:22
          at validateEntries (file:///Users/ingof/Dev/GitHub/official-matter.js/packages/node/dist/esm/behavior/state/validation/ValueValidator.js:235:11) {
        code: 135,
        clusterCode: undefined
      }
    }
  ]
}


```
