### ISSUE TITLE
Resuming after a restart on bridge

### ISSUE THREAD

**Issue by mow** [project-chip/matter.js#170]
Hello,

while using BridgedDeviceNode I'm encountering a problem, whenever bridge restarts none of the paired devices can resume it's session, e.g. whenever I try to switch the light on or off  the error is like following (repeated 5 times);

.....`Device is already commissioned. Waiting for controllers to connect ...
2023-05-30 11:11:00.998 DEBUG UdpChannelNode Initialize multicast address: :5353 interface: wlan0 type: udp4
2023-05-30 11:11:00.999 DEBUG UdpChannelNode Initialize multicast address: : interface: wlan0 type: udp6

2023-05-30 11:11:25.826 ERROR ExchangeManager Cannot find a session for ID 49055
    at ExchangeManager.<anonymous> (/home/xxx/projects/matter/matter-js-dev/packages/matter.js/src/protocol/ExchangeManager.ts:92:42)
    at Generator.next (<anonymous>)
    at /home/xxx/projects/matter/matter-js-dev/packages/matter.js/dist/cjs/protocol/ExchangeManager.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xxx/projects/matter/matter-js-dev/packages/matter.js/dist/cjs/protocol/ExchangeManager.js:9:12)
    at ExchangeManager.onMessage (/home/xxx/projects/matter/matter-js-dev/packages/matter.js/dist/cjs/protocol/ExchangeManager.js:77:16)
    at /home/xxx/projects/matter/matter-js-dev/packages/matter.js/src/protocol/ExchangeManager.ts:57:18
    at /home/xxx/projects/matter/matter-js-dev/packages/matter.js/src/net/UdpInterface.ts:28:83
    at Socket.messageListener (/home/xxx/projects/matter/matter-js-dev/packages/matter-node.js/src/net/UdpChannelNode.ts:58:13)
    at Socket.emit (node:events:513:28)`...

after 5th error I assume a new session id is being determined by the controller and it resumes to normal operation:

.......`
2023-05-30 11:12:12.785 DEBUG MessageExchange New exchange protocol: 0 id: 44676 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
2023-05-30 11:12:12.786 DEBUG MessageExchange Message « id: 0/44676/140446173 type: 0/48 reqAck: true payload: 15300120ff610ee0`..........

I tried to trigger some events like reachableChanged / startup but nothing changed (i assume they are internal) as thinking that this is the better way in terms of communications, but if we can't announce can we make session permanent with it's id?

**Comment by Apollon77** [comment]
No this is normal behavior. The controller knows a session and uses this for a certain amount of time. When you restart the device then this session does not exist any longer. So the next try to communicate the controller do not know if the restart and tries to use that old session. There is no way (from my spec knowledge) to tell the controller "hey session is not existing, do a new one". 
So the controller tries 5times with defined backoff times. 

After that the controller should try to resume a session as you also stated. So in such a case it might need 15+ seconds but then a new session should be established automatically by the controller. Sometimes you need to execute the command a second time. 

Does that match?

**Comment by Apollon77** [comment]
From first check the events do not really make any difference ... so I would accept that for now.

the alternative would be to store existing sessions, but also chip is not doing that ...
