### ISSUE TITLE
ERROR InteractionMessenger TypeError: attribute.addMatterListener is not a function

### ISSUE THREAD

**Issue by adminy** [project-chip/matter.js#219]
The logs for this are [here](https://logpaste.com/kWwIgEoG) and the full code for this is [here](https://github.com/adminy/home/blob/master/index.js)

But all I was trying to do is understand how to create custom devices.
So instead of :
```javascript
import { OnOffLightDevice, OnOffPluginUnitDevice } from '@project-chip/matter.js/device'
//----
new OnOffLightDevice()
new OnOffPluginUnitDevice()
```
I was trying this:
```javascript
import { DeviceTypes, Device } from '@project-chip/matter.js/device'
import {
	createDefaultOnOffClusterServer,
	createDefaultGroupsClusterServer,
	createDefaultScenesClusterServer,
	createDefaultIdentifyClusterServer
} from '@project-chip/matter.js/cluster'
class OnOffDevice extends Device {
   constructor(type) {
      super(type, {})
      const cluster = createDefaultOnOffClusterServer()
      
      const clusterServers = [
         createDefaultIdentifyClusterServer({
	    identify: data => this._executeHandler('identify', data)
	 }),
         createDefaultGroupsClusterServer(),
	 createDefaultScenesClusterServer(),
         cluster
      ]
      for (const server of clusterServers)
         this.addClusterServer(server)

      this.onOff = state => cluster.setOnOffAttribute(state)
      this.toggle = () => this.onOff(!cluster.getOnOffAttribute())
      cluster.subscribeOnOffAttribute(state => { 
         console.log('state changed here', state)
      })
      this.addCommandHandler('identify', ({ request: { identifyTime } }) =>
         console.log(`Identify OnOffDevice: ${identifyTime}`))
    }
}
//----
new OnOffDevice(DeviceTypes.ON_OFF_PLUGIN_UNIT)
new OnOffDevice(DeviceTypes.ON_OFF_LIGHT)
```

And I got the following error:
```
ERROR InteractionMessenger TypeError: attribute.addMatterListener is not a function
    at /root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/SubscriptionHandler.js:61:23
    at Array.forEach (<anonymous>)
    at new SubscriptionHandler (/root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/SubscriptionHandler.js:55:20)
    at InteractionServer.<anonymous> (/root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/InteractionServer.js:471:45)
    at Generator.next (<anonymous>)
    at /root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/InteractionServer.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/InteractionServer.js:9:12)
    at InteractionServer.handleSubscribeRequest (/root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/InteractionServer.js:437:16)
    at /root/home/matter.js/packages/matter.js/dist/cjs/protocol/interaction/InteractionServer.js:335:265
```

**Comment by Apollon77** [comment]
@adminy Please ry with current main branch

**Comment by Apollon77** [comment]
Please reopen if it happens again with current versions
