### ISSUE TITLE
[ble][pair] crash on scan

### ISSUE THREAD

**Issue by turon** [project-chip/matter.js#281]
```
matter-node> pair -b
Error [object Promise]
matter-node> 2023-08-16 13:44:46.330 DEBUG UdpChannelNode Socket created and bound  remoteAddress: undefined:undefined localAddress: :::47487
2023-08-16 13:44:46.348 DEBUG BleScanner Registered waiter for query D:3840 with timeout 15 seconds
2023-08-16 13:44:46.348 DEBUG NobleBleClient noble state is not poweredOn ... delay scanning till poweredOn
2023-08-16 13:44:46.499 DEBUG NobleBleClient Noble state changed to poweredOn
2023-08-16 13:44:46.499 DEBUG NobleBleClient Start scanning for Matter Services ...
2023-08-16 13:45:01.348 DEBUG BleScanner Finishing waiter for query D:3840, resolving: true
2023-08-16 13:45:01.355 WARN CommissioningController Ble commissioning failed: Error: No device discovered using identifier {"longDiscriminator":3840}! Please check that the relevant device is online.
2023-08-16 13:45:01.355 DEBUG MatterController Server addresses to try: udp://::1:5541
2023-08-16 13:45:01.355 DEBUG MatterController Try to communicate with udp://::1:5541 ...
2023-08-16 13:45:01.356 DEBUG MessageExchange New exchange protocol: 0 id: 46787 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
2023-08-16 13:45:01.357 DEBUG ExchangeManager Message » id: 0/46787/3358292387 type: 0/32 reqAck: true payload: 15300120f90a0fd79b3770469079fb793b0c05e6e74251cf0d03083b97582be65dc4639f2502f2cd240300280418
2023-08-16 13:45:01.729 DEBUG MessageExchange Resubmit message 3358292387 (attempt 1, next backoff time 392ms))
2023-08-16 13:45:01.729 DEBUG ExchangeManager Message » id: 0/46787/3358292387 type: 0/32 reqAck: true payload: 15300120f90a0fd79b3770469079fb793b0c05e6e74251cf0d03083b97582be65dc4639f2502f2cd240300280418
2023-08-16 13:45:02.123 DEBUG MessageExchange Resubmit message 3358292387 (attempt 2, next backoff time 556ms))
2023-08-16 13:45:02.124 DEBUG ExchangeManager Message » id: 0/46787/3358292387 type: 0/32 reqAck: true payload: 15300120f90a0fd79b3770469079fb793b0c05e6e74251cf0d03083b97582be65dc4639f2502f2cd240300280418
2023-08-16 13:45:02.680 DEBUG MessageExchange Resubmit message 3358292387 (attempt 3, next backoff time 871ms))
2023-08-16 13:45:02.680 DEBUG ExchangeManager Message » id: 0/46787/3358292387 type: 0/32 reqAck: true payload: 15300120f90a0fd79b3770469079fb793b0c05e6e74251cf0d03083b97582be65dc4639f2502f2cd240300280418
2023-08-16 13:45:03.552 DEBUG MessageExchange Resubmit message 3358292387 (attempt 4, next backoff time 1616ms))
2023-08-16 13:45:03.552 DEBUG ExchangeManager Message » id: 0/46787/3358292387 type: 0/32 reqAck: true payload: 15300120f90a0fd79b3770469079fb793b0c05e6e74251cf0d03083b97582be65dc4639f2502f2cd240300280418
2023-08-16 13:45:05.172 DEBUG MatterController Failed to communicate with udp://::1:5541, try next server ... Error
    at MessageExchange.retransmitMessage (/home/mturon/src/nest/matter.js/packages/matter.js/src/protocol/MessageExchange.ts:288:44)
    at TimerNode.callback (/home/mturon/src/nest/matter.js/packages/matter.js/src/protocol/MessageExchange.ts:309:26)
    at Timeout._onTimeout (/home/mturon/src/nest/matter.js/packages/matter-node.js/src/time/TimeNode.ts:26:18)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
2023-08-16 13:45:05.187 DEBUG MatterController Server addresses to try: udp://::1:5541
2023-08-16 13:45:05.188 DEBUG MdnsScanner Registered waiter for query _L3840._sub._matterc._udp.local with timeout 15 seconds
2023-08-16 13:45:05.189 DEBUG MdnsScanner Set 2 query records for query _L3840._sub._matterc._udp.local: [{"name":"_matterc._udp.local","recordClass":1,"recordType":12},{"name":"_L3840._sub._matterc._udp.local","recordClass":1,"recordType":12}]
2023-08-16 13:45:05.190 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 1.5 seconds
2023-08-16 13:45:05.192 DEBUG UdpChannelNode Socket created and bound  remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
2023-08-16 13:45:05.192 DEBUG UdpChannelNode Socket created and bound  remoteAddress: undefined:5353 localAddress: :::5353
2023-08-16 13:45:05.193 DEBUG UdpChannelNode Initialize multicast address: 100.86.180.251:5353 interface: wlp0s20f3 type: udp4
2023-08-16 13:45:05.193 DEBUG UdpChannelNode Initialize multicast address: ::%wlp0s20f3:5353 interface: wlp0s20f3 type: udp6
2023-08-16 13:45:06.692 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 3 seconds
2023-08-16 13:45:09.693 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 6 seconds
2023-08-16 13:45:15.693 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 12 seconds
2023-08-16 13:45:20.189 DEBUG MdnsScanner Finishing waiter for query _L3840._sub._matterc._udp.local, resolving: true
2023-08-16 13:45:20.190 DEBUG MdnsScanner Removing last query _L3840._sub._matterc._udp.local and stopping announce timer
/home/mturon/src/nest/matter.js/packages/matter.js/src/MatterController.ts:181
            throw new CommissioningError(
                  ^
CommissioningError: No device discovered using identifier {"longDiscriminator":3840}! Please check that the relevant device is online.
    at MatterController.<anonymous> (/home/mturon/src/nest/matter.js/packages/matter.js/src/MatterController.ts:181:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/mturon/src/nest/matter.js/packages/matter.js/dist/cjs/MatterController.js:10:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by Apollon77** [comment]
Log shows:
* no BLE commissioned device found within the 15s he tries that right now, se he switched to UDP
* Then he found a device on localhost port 5541 ... but in fact not found because it was "there" ... I need to check where it came from. I assume you do not know the exact config anymmore @turon 
* That localhost device was not working
* He then scanned 15 more seconds and found nothing, so he finally failed

**Comment by Apollon77** [comment]
without more details, not reproducable
