### ISSUE TITLE
Find PASE issue that appeasrs sometimes with chip-tool

### ISSUE THREAD

**Issue by Apollon77** [project-chip/matter.js#312]
Broken:

```
[1694776311956] [22620:7155901] [DIS] Discovered node:
[1694776311956] [22620:7155901] [DIS] 	Hostname: 88665A443C4C0000
[1694776311956] [22620:7155901] [DIS] 	IP Address #1: fe80::419:56de:f7c4:1373
[1694776311956] [22620:7155901] [DIS] 	IP Address #2: 2a02:8071:2c87:399c:8a0:8914:4763:faad
[1694776311956] [22620:7155901] [DIS] 	IP Address #3: 2a02:8071:2c87:399c:b82f:d512:4247:a73b
[1694776311956] [22620:7155901] [DIS] 	IP Address #4: 2a02:8071:2c87:399c:cea:d64d:8892:1141
[1694776311956] [22620:7155901] [DIS] 	IP Address #5: fd00::10a4:fa22:87a6:330c
[1694776311956] [22620:7155901] [DIS] 	Port: 5540
[1694776311956] [22620:7155901] [DIS] 	Mrp Interval idle: 5000 ms
[1694776311956] [22620:7155901] [DIS] 	Mrp Interval active: 300 ms
[1694776311956] [22620:7155901] [DIS] 	TCP Supported: 0
[1694776311956] [22620:7155901] [DIS] 	Device Name: Testdevice
[1694776311956] [22620:7155901] [DIS] 	Vendor ID: 65521
[1694776311956] [22620:7155901] [DIS] 	Product ID: 32769
[1694776311956] [22620:7155901] [DIS] 	Device Type: 266
[1694776311956] [22620:7155901] [DIS] 	Long Discriminator: 3840
[1694776311956] [22620:7155901] [DIS] 	Pairing Hint: 33
[1694776311956] [22620:7155901] [DIS] 	Instance Name: 2C925FE2E3AE7453
[1694776311956] [22620:7155901] [DIS] 	Commissioning Mode: 2
[1694776311956] [22620:7155901] [TOO] Discovered Device: fe80::419:56de:f7c4:1373:5540
[1694776311958] [22620:7155901] [DIS] Mdns: Resolve failure (src/platform/Darwin/DnssdImpl.cpp:409: CHIP Error 0x00000074: The operation has been cancelled)
[1694776311958] [22620:7155901] [DIS] Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:412: CHIP Error 0x00000074: The operation has been cancelled)
[1694776311962] [22620:7155901] [IN] SecureSession[0x6000019a6d00]: Allocated Type:1 LSID:16149
[1694776311962] [22620:7155901] [SC] Assigned local session key ID 16149
[1694776311963] [22620:7155901] [EM] <<< [E:41618i S:0 M:22214771] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
[1694776311963] [22620:7155901] [IN] (U) Sending msg 22214771 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776311964] [22620:7155901] [SC] Sent PBKDF param request
[1694776311964] [22620:7155901] [CTL] Setting attestation nonce to random value
[1694776311964] [22620:7155901] [CTL] Setting CSR nonce to random value
[1694776311964] [22620:7155901] [CTL] Commission called for node ID 0x0000000012344321
2023-09-15 13:11:52.057 DEBUG MdnsBroadcaster Announcement: Commission mode  mode: 2 qname: 2C925FE2E3AE7453._matterc._udp.local port: 5540 interface: lo0
2023-09-15 13:11:52.059 DEBUG MessageExchange New exchange protocol: 0 id: 41618 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
2023-09-15 13:11:52.060 DEBUG MessageExchange Message « id: 0/41618/22214771 type: 0/32 reqAck: true payload: 153001208fcea75271777e35bbdfab0f8f5951ed9855dc5e4e660ae4038cef48abb681ef2502153f240300280418
2023-09-15 13:11:52.061 INFO PaseServer Pase server: Received pairing request from udp://fe80::1c3e:5f63:6021:c8f5%en0:64471.
2023-09-15 13:11:52.063 DEBUG ExchangeManager Message » id: 0/41618/1709157883 type: 0/33 acked: 22214771 reqAck: true payload: 153001208fcea75271777e35bbdfab0f8f5951ed9855dc5e4e660ae4038cef48abb681ef3002209984b95d2d79769c2c0429e9e31b9b5fb55843c08d1151cce983281e7c8a45ba250388e835042501e8033002203d57cd5a6a5e49b07fd0a801513cb64c547c0ee9eda2b8b28c6cb1d15e9c559e1818

 RUNS  test-chip/ChipTestRunner.ts
[1694776312065] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157883 (Ack:22214771)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:21 (SecureChannel:PBKDFParamResponse)
[1694776312065] [22620:7155901] [EM] Found matching exchange: 41618i, Delegate: 0x7fd7afae2a50
[1694776312065] [22620:7155901] [EM] Rxd Ack; Removing MessageCounter:22214771 from Retrans Table on exchange 41618i
[1694776312065] [22620:7155901] [SC] Received PBKDF param response
[1694776312066] [22620:7155901] [SC] Peer assigned session ID 59528
[1694776312087] [22620:7155901] [EM] <<< [E:41618i S:0 M:22214772 (Ack:1709157883)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:22 (SecureChannel:PASE_Pake1)
[1694776312087] [22620:7155901] [IN] (U) Sending msg 22214772 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776312087] [22620:7155901] [SC] Sent spake2p msg1
2023-09-15 13:11:52.088 DEBUG MessageExchange Message « id: 0/41618/22214772 type: 0/34 acked: 1709157883 reqAck: true payload: 15300141040b3606f9bf1f5e435b0750af6e98f8e93735ba3bbbc7e906a10bea6cfba1486cc84d2fe86d1d928e80dc84608bbd04b3182a5deab5e4b0981b357d1786688b2318

 RUNS  test-chip/ChipTestRunner.ts
[1694776312429] [22620:7155901] [EM] Retransmitting MessageCounter:22214772 on exchange 41618i Send Cnt 1
[1694776312430] [22620:7155901] [IN] (U) Sending msg 22214772 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776312830] [22620:7155901] [EM] Retransmitting MessageCounter:22214772 on exchange 41618i Send Cnt 2
[1694776312831] [22620:7155901] [IN] (U) Sending msg 22214772 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776313372] [22620:7155900] [EM] Retransmitting MessageCounter:22214772 on exchange 41618i Send Cnt 3
[1694776313372] [22620:7155900] [IN] (U) Sending msg 22214772 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
2023-09-15 13:11:55.605 DEBUG MessageExchange Message « id: 0/41618/22214772 type: 0/34 acked: 1709157883 reqAck: true payload: 15300141040b3606f9bf1f5e435b0750af6e98f8e93735ba3bbbc7e906a10bea6cfba1486cc84d2fe86d1d928e80dc84608bbd04b3182a5deab5e4b0981b357d1786688b2318
2023-09-15 13:11:55.605 DEBUG ExchangeManager Message » id: 0/41618/1709157884 type: 0/16 acked: 22214772 reqAck: false payload: 
2023-09-15 13:11:55.606 DEBUG MessageExchange Message « id: 0/41618/22214772 type: 0/34 acked: 1709157883 reqAck: true payload: 15300141040b3606f9bf1f5e435b0750af6e98f8e93735ba3bbbc7e906a10bea6cfba1486cc84d2fe86d1d928e80dc84608bbd04b3182a5deab5e4b0981b357d1786688b2318
2023-09-15 13:11:55.606 DEBUG ExchangeManager Message » id: 0/41618/1709157885 type: 0/16 acked: 22214772 reqAck: false payload: 
2023-09-15 13:11:55.607 DEBUG MessageExchange Message « id: 0/41618/22214772 type: 0/34 acked: 1709157883 reqAck: true payload: 15300141040b3606f9bf1f5e435b0750af6e98f8e93735ba3bbbc7e906a10bea6cfba1486cc84d2fe86d1d928e80dc84608bbd04b3182a5deab5e4b0981b357d1786688b2318
2023-09-15 13:11:55.607 DEBUG ExchangeManager Message » id: 0/41618/1709157886 type: 0/16 acked: 22214772 reqAck: false payload: 
2023-09-15 13:11:55.607 DEBUG MessageExchange Message « id: 0/41618/22214772 type: 0/34 acked: 1709157883 reqAck: true payload: 15300141040b3606f9bf1f5e435b0750af6e98f8e93735ba3bbbc7e906a10bea6cfba1486cc84d2fe86d1d928e80dc84608bbd04b3182a5deab5e4b0981b357d1786688b2318
2023-09-15 13:11:55.608 DEBUG ExchangeManager Message » id: 0/41618/1709157887 type: 0/16 acked: 22214772 reqAck: false payload: 

 RUNS  test-chip/ChipTestRunner.ts
[1694776315613] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157884 (Ack:22214772)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776315613] [22620:7155901] [EM] Found matching exchange: 41618i, Delegate: 0x7fd7afae2a50
[1694776315613] [22620:7155901] [EM] Rxd Ack; Removing MessageCounter:22214772 from Retrans Table on exchange 41618i
[1694776315613] [22620:7155901] [DL] _OnPlatformEvent
[1694776315613] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157885 (Ack:22214772)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776315613] [22620:7155901] [EM] Found matching exchange: 41618i, Delegate: 0x7fd7afae2a50
[1694776315613] [22620:7155901] [EM] CHIP MessageCounter:22214772 not in RetransTable on exchange 41618i
[1694776315613] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157886 (Ack:22214772)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776315613] [22620:7155901] [EM] Found matching exchange: 41618i, Delegate: 0x7fd7afae2a50
[1694776315613] [22620:7155901] [EM] CHIP MessageCounter:22214772 not in RetransTable on exchange 41618i
[1694776315613] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157887 (Ack:22214772)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-09-15 13:11:55.645 DEBUG ExchangeManager Message » id: 0/41618/1709157888 type: 0/35 acked: 22214772 reqAck: true payload: 1530014104fab614db9bd337b2dea25c3c7fc8c747eb4be46f6428dc1f252833d2199eebac97e6c75c2a07cb0cd689c1fb9c086803dda9ba444f69d96a1d0d36492e3ea275300220ebed1b6db30042986189b947f3705e76237c53d19ef9691dfa2a161d6af56e7618

 RUNS  test-chip/ChipTestRunner.ts
[1694776315646] [22620:7155901] [EM] >>> [E:41618i S:0 M:1709157888 (Ack:22214772)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:23 (SecureChannel:PASE_Pake2)
[1694776315646] [22620:7155901] [EM] Found matching exchange: 41618i, Delegate: 0x7fd7afae2a50
[1694776315646] [22620:7155901] [EM] CHIP MessageCounter:22214772 not in RetransTable on exchange 41618i
[1694776315646] [22620:7155901] [SC] Received spake2p msg2
[1694776315659] [22620:7155901] [SC] Failed to verify peer's MAC. This can happen when setup code is incorrect.
[1694776315659] [22620:7155901] [SC] Sending status report. Protocol code 2, exchange 41618
[1694776315659] [22620:7155901] [EM] <<< [E:41618i S:0 M:22214773 (Ack:1709157888)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
[1694776315660] [22620:7155901] [IN] (U) Sending msg 22214773 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776315660] [22620:7155901] [IN] SecureSession[0x6000019a6d00]: Released - Type:1 LSID:16149
[1694776315660] [22620:7155901] [SC] Failed during PASE session setup: src/crypto/CHIPCryptoPALOpenSSL.cpp:1437: CHIP Error 0x000000AC: Internal error
[1694776315660] [22620:7155901] [TOO] Secure Pairing Failed

```

Working:
```
[1694776595901] [22911:7162013] [DIS] Discovered node:
[1694776595901] [22911:7162013] [DIS] 	Hostname: 88665A443C4C0000
[1694776595901] [22911:7162013] [DIS] 	IP Address #1: fe80::419:56de:f7c4:1373
[1694776595901] [22911:7162013] [DIS] 	IP Address #2: 2a02:8071:2c87:399c:8a0:8914:4763:faad
[1694776595901] [22911:7162013] [DIS] 	IP Address #3: 2a02:8071:2c87:399c:b82f:d512:4247:a73b
[1694776595901] [22911:7162013] [DIS] 	IP Address #4: 2a02:8071:2c87:399c:cea:d64d:8892:1141
[1694776595901] [22911:7162013] [DIS] 	IP Address #5: fd00::10a4:fa22:87a6:330c
[1694776595901] [22911:7162013] [DIS] 	Port: 5540
[1694776595901] [22911:7162013] [DIS] 	Mrp Interval idle: 5000 ms
[1694776595901] [22911:7162013] [DIS] 	Mrp Interval active: 300 ms
[1694776595901] [22911:7162013] [DIS] 	TCP Supported: 0
[1694776595901] [22911:7162013] [DIS] 	Device Name: Testdevice
[1694776595902] [22911:7162013] [DIS] 	Vendor ID: 65521
[1694776595902] [22911:7162013] [DIS] 	Product ID: 32769
[1694776595902] [22911:7162013] [DIS] 	Device Type: 266
[1694776595902] [22911:7162013] [DIS] 	Long Discriminator: 3840
[1694776595902] [22911:7162013] [DIS] 	Pairing Hint: 33
[1694776595902] [22911:7162013] [DIS] 	Instance Name: 4E1B2B1F354181E3
[1694776595902] [22911:7162013] [DIS] 	Commissioning Mode: 2
[1694776595902] [22911:7162013] [TOO] Discovered Device: fe80::419:56de:f7c4:1373:5540
[1694776595904] [22911:7162013] [DIS] Mdns: Resolve failure (src/platform/Darwin/DnssdImpl.cpp:409: CHIP Error 0x00000074: The operation has been cancelled)
[1694776595904] [22911:7162013] [DIS] Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:412: CHIP Error 0x00000074: The operation has been cancelled)
[1694776595907] [22911:7162013] [IN] SecureSession[0x60000034cd00]: Allocated Type:1 LSID:10118
[1694776595908] [22911:7162013] [SC] Assigned local session key ID 10118
[1694776595908] [22911:7162013] [EM] <<< [E:48917i S:0 M:90917047] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
[1694776595908] [22911:7162013] [IN] (U) Sending msg 90917047 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776595908] [22911:7162013] [SC] Sent PBKDF param request
[1694776595908] [22911:7162013] [CTL] Setting attestation nonce to random value
[1694776595909] [22911:7162013] [CTL] Setting CSR nonce to random value
[1694776595909] [22911:7162013] [CTL] Commission called for node ID 0x0000000012344321
2023-09-15 13:16:35.911 DEBUG MessageExchange New exchange protocol: 0 id: 48917 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
2023-09-15 13:16:35.911 DEBUG MessageExchange Message « id: 0/48917/90917047 type: 0/32 reqAck: true payload: 15300120ca377440f86e132c13f1f447ac257156b20fd37f3537ccae7b3b855ffd466aea25028627240300280418
2023-09-15 13:16:35.912 INFO PaseServer Pase server: Received pairing request from udp://fe80::1c3e:5f63:6021:c8f5%en0:52832.
2023-09-15 13:16:35.915 DEBUG ExchangeManager Message » id: 0/48917/3938357974 type: 0/33 acked: 90917047 reqAck: true payload: 15300120ca377440f86e132c13f1f447ac257156b20fd37f3537ccae7b3b855ffd466aea3002200b179cd353692e329576e8bb763adb64987d4d5aded986e691adb0b6d483e8e92503d9d635042501e8033002204e25bd62ac7f6ddf1bb28e0ac0567881f05012947a56684496a8362f6a19f0f01818

 RUNS  test-chip/ChipTestRunner.ts
[1694776595918] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357974 (Ack:90917047)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:21 (SecureChannel:PBKDFParamResponse)
[1694776595918] [22911:7162013] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776595918] [22911:7162013] [EM] Rxd Ack; Removing MessageCounter:90917047 from Retrans Table on exchange 48917i
[1694776595918] [22911:7162013] [SC] Received PBKDF param response
 RUNS  test-chip/ChipTestRunner.ts
[1694776595939] [22911:7162013] [EM] <<< [E:48917i S:0 M:90917048 (Ack:3938357974)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:22 (SecureChannel:PASE_Pake1)
[1694776595939] [22911:7162013] [IN] (U) Sending msg 90917048 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776595939] [22911:7162013] [SC] Sent spake2p msg1
2023-09-15 13:16:35.942 DEBUG MessageExchange Message « id: 0/48917/90917048 type: 0/34 acked: 3938357974 reqAck: true payload: 15300141048b9738ad1e72cd08038ec2c5616e13aa8c016b2d0528fce5dabbcb6d286b33048eb4352c71edba7009ca14b9694034275375a88648d1af044889f5cfbc73392e18

 RUNS  test-chip/ChipTestRunner.ts
[1694776596326] [22911:7162013] [EM] Retransmitting MessageCounter:90917048 on exchange 48917i Send Cnt 1
[1694776596327] [22911:7162013] [IN] (U) Sending msg 90917048 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776596729] [22911:7162012] [EM] Retransmitting MessageCounter:90917048 on exchange 48917i Send Cnt 2
[1694776596730] [22911:7162012] [IN] (U) Sending msg 90917048 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776597260] [22911:7162013] [EM] Retransmitting MessageCounter:90917048 on exchange 48917i Send Cnt 3
[1694776597260] [22911:7162013] [IN] (U) Sending msg 90917048 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
2023-09-15 13:16:39.182 DEBUG MessageExchange Message « id: 0/48917/90917048 type: 0/34 acked: 3938357974 reqAck: true payload: 15300141048b9738ad1e72cd08038ec2c5616e13aa8c016b2d0528fce5dabbcb6d286b33048eb4352c71edba7009ca14b9694034275375a88648d1af044889f5cfbc73392e18
2023-09-15 13:16:39.183 DEBUG ExchangeManager Message » id: 0/48917/3938357975 type: 0/16 acked: 90917048 reqAck: false payload: 
2023-09-15 13:16:39.183 DEBUG MessageExchange Message « id: 0/48917/90917048 type: 0/34 acked: 3938357974 reqAck: true payload: 15300141048b9738ad1e72cd08038ec2c5616e13aa8c016b2d0528fce5dabbcb6d286b33048eb4352c71edba7009ca14b9694034275375a88648d1af044889f5cfbc73392e18
2023-09-15 13:16:39.183 DEBUG ExchangeManager Message » id: 0/48917/3938357976 type: 0/16 acked: 90917048 reqAck: false payload: 
2023-09-15 13:16:39.183 DEBUG MessageExchange Message « id: 0/48917/90917048 type: 0/34 acked: 3938357974 reqAck: true payload: 15300141048b9738ad1e72cd08038ec2c5616e13aa8c016b2d0528fce5dabbcb6d286b33048eb4352c71edba7009ca14b9694034275375a88648d1af044889f5cfbc73392e18
2023-09-15 13:16:39.184 DEBUG ExchangeManager Message » id: 0/48917/3938357977 type: 0/16 acked: 90917048 reqAck: false payload: 
2023-09-15 13:16:39.184 DEBUG MessageExchange Message « id: 0/48917/90917048 type: 0/34 acked: 3938357974 reqAck: true payload: 15300141048b9738ad1e72cd08038ec2c5616e13aa8c016b2d0528fce5dabbcb6d286b33048eb4352c71edba7009ca14b9694034275375a88648d1af044889f5cfbc73392e18
2023-09-15 13:16:39.184 DEBUG ExchangeManager Message » id: 0/48917/3938357978 type: 0/16 acked: 90917048 reqAck: false payload: 
2023-09-15 13:16:39.190 DEBUG ExchangeManager Message » id: 0/48917/3938357979 type: 0/35 acked: 90917048 reqAck: true payload: 1530014104b5ecda475331b82b0833d01ceb9ef3cb0560627580b6ee54e3b8ee92644e5fcaf58d3ae9c550619eee3ab32c6046af6bc05a2cd7ed4eda8abbea2b30430963ff3002202cdd4d9f3a6a2e9a2927d7505388cda2f7eb07ba0522ff3a158398f6b465fd1018

 RUNS  test-chip/ChipTestRunner.ts
[1694776599190] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357976 (Ack:90917048)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776599190] [22911:7162013] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776599190] [22911:7162013] [EM] Rxd Ack; Removing MessageCounter:90917048 from Retrans Table on exchange 48917i
[1694776599190] [22911:7162013] [DL] _OnPlatformEvent
[1694776599191] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357977 (Ack:90917048)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776599191] [22911:7162013] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776599191] [22911:7162013] [EM] CHIP MessageCounter:90917048 not in RetransTable on exchange 48917i
[1694776599191] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357978 (Ack:90917048)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1694776599191] [22911:7162013] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776599191] [22911:7162013] [EM] CHIP MessageCounter:90917048 not in RetransTable on exchange 48917i
[1694776599191] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357979 (Ack:90917048)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:23 (SecureChannel:PASE_Pake2)
[1694776599191] [22911:7162013] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776599191] [22911:7162013] [EM] CHIP MessageCounter:90917048 not in RetransTable on exchange 48917i
[1694776599192] [22911:7162013] [SC] Received spake2p msg2
[1694776599203] [22911:7162013] [EM] <<< [E:48917i S:0 M:90917049 (Ack:3938357979)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:24 (SecureChannel:PASE_Pake3)
[1694776599203] [22911:7162013] [IN] (U) Sending msg 90917049 to IP address 'UDP:[fe80::419:56de:f7c4:1373%en7]:5540'
[1694776599204] [22911:7162013] [SC] Sent spake2p msg3
[1694776599204] [22911:7162013] [DL] _OnPlatformEvent
[1694776599204] [22911:7162013] [EM] >>> [E:48917i S:0 M:3938357975 (Ack:90917048)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-09-15 13:16:39.206 DEBUG MessageExchange Message « id: 0/48917/90917049 type: 0/36 acked: 3938357979 reqAck: true payload: 1530012086f420a052224375bfd1d4020ae423192043fb83f765c6522970e54387be0c6518
2023-09-15 13:16:39.207 DEBUG SecureSession Created secure PASE session for fabric index undefined secure/55001
2023-09-15 13:16:39.207 INFO PaseServer Pase server: session 55001 created with udp://fe80::1c3e:5f63:6021:c8f5%en0:52832.
2023-09-15 13:16:39.208 DEBUG ExchangeManager Message » id: 0/48917/3938357980 type: 0/64 acked: 90917049 reqAck: true payload: 0000000000000000

 RUNS  test-chip/ChipTestRunner.ts
[1694776599209] [22911:7162012] [EM] >>> [E:48917i S:0 M:3938357980 (Ack:90917049)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
[1694776599209] [22911:7162012] [EM] Found matching exchange: 48917i, Delegate: 0x7f9c6e5bca50
[1694776599209] [22911:7162012] [EM] Rxd Ack; Removing MessageCounter:90917049 from Retrans Table on exchange 48917i
[1694776599209] [22911:7162012] [SC] SecureSession[0x60000034cd00, LSID:10118]: State change 'kEstablishing' --> 'kActive'
[1694776599209] [22911:7162012] [IN] SecureSession[0x60000034cd00]: Activated - Type:1 LSID:10118
[1694776599209] [22911:7162012] [IN] New secure session activated for device <FFFFFFFB00000000, 0>, LSID:10118 PSID:55001!
[1694776599209] [22911:7162012] [CTL] Remote device completed SPAKE2+ handshake
[1694776599209] [22911:7162012] [TOO] Pairing Success
[1694776599209] [22911:7162012] [TOO] PASE establishment successful
[1694776599209] [22911:7162012] [CTL] Commissioning stage next step: 'SecurePairing' -> 'ReadCommissioningInfo'

```

**Comment by Apollon77** [comment]
I also had one time a comparable issues in Integrationtest:

```
  2023-10-13 13:28:17.008 DEBUG MessageExchange      New exchange protocol: 0 id: 57875 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
  2023-10-13 13:28:17.008 DEBUG ExchangeManager      Message » id: 0/57875/1658110430 type: 0/32 reqAck: true payload: 15300120d422ee30e0248c93bc4a40c27ba4323af34b96138896ebebff897745e125bbb225020b64240300280418
  2023-10-13 13:28:17.008 DEBUG MessageExchange      New exchange protocol: 0 id: 57875 active retransmit ms: 300 idle retransmit ms: 5000 retries: 5
  2023-10-13 13:28:17.008 DEBUG MessageExchange      Message « id: 0/57875/1658110430 type: 0/32 reqAck: true payload: 15300120d422ee30e0248c93bc4a40c27ba4323af34b96138896ebebff897745e125bbb225020b64240300280418
  2023-10-13 13:28:17.008 INFO  PaseServer           Received pairing request from udp://fdce:7c65:b2dd:7d46:923f:8a53:eb6c:cafe:54355.
  2023-10-13 13:28:17.008 DEBUG ExchangeManager      Message » id: 0/57875/153890942 type: 0/33 acked: 1658110430 reqAck: true payload: 15300120d422ee30e0248c93bc4a40c27ba4323af34b96138896ebebff897745e125bbb2300220260f95d1606a63c0951e05db8c484d52d14d6745ddc438063b89cae17ae8264c250372ed35042501e803300220d1b8db8ae5be0107fa1077d0e65537283f290a42e1cd036f90b1188cf927a8fd1818
  2023-10-13 13:28:17.008 DEBUG MessageExchange      Message « id: 0/57875/153890942 type: 0/33 acked: 1658110430 reqAck: true payload: 15300120d422ee30e0248c93bc4a40c27ba4323af34b96138896ebebff897745e125bbb2300220260f95d1606a63c0951e05db8c484d52d14d6745ddc438063b89cae17ae8264c250372ed35042501e803300220d1b8db8ae5be0107fa1077d0e65537283f290a42e1cd036f90b1188cf927a8fd1818
  2023-10-13 13:28:17.018 DEBUG ExchangeManager      Message » id: 0/57875/1658110431 type: 0/34 acked: 153890942 reqAck: true payload: 15300141049e0f1c79387acff5a5aff951d9cbfdac0858372cfe97fd719a4628393b7e7d1c32837ea05607c0932543b76b01c4cb650a5ae22b58fa9c2a4fa028317201fc8218
  2023-10-13 13:28:17.018 DEBUG MessageExchange      Message « id: 0/57875/1658110431 type: 0/34 acked: 153890942 reqAck: true payload: 15300141049e0f1c79387acff5a5aff951d9cbfdac0858372cfe97fd719a4628393b7e7d1c32837ea05607c0932543b76b01c4cb650a5ae22b58fa9c2a4fa028317201fc8218
  2023-10-13 13:28:17.026 ERROR PaseServer           An error occurred during the PASE commissioning. Unknown point format
      at ShortCurve.decodePoint (/Users/ingof/Dev/GitHub/matter.js/node_modules/elliptic/lib/elliptic/curve/base.js:291:9)
      at Spake2p.computeSecretAndVerifiersFromX (/Users/ingof/Dev/GitHub/matter.js/packages/matter.js/src/crypto/Spake2p.ts:72:35)
      at PaseServer.handlePairingRequest (/Users/ingof/Dev/GitHub/matter.js/packages/matter.js/src/session/pase/PaseServer.ts:118:48)
      at PaseServer.onNewExchange (/Users/ingof/Dev/GitHub/matter.js/packages/matter.js/src/session/pase/PaseServer.ts:57:13)
      at SecureChannelProtocol.onNewExchange (/Users/ingof/Dev/GitHub/matter.js/packages/matter.js/src/protocol/securechannel/SecureChannelProtocol.ts:59:21)
      at ExchangeManager.onMessage (/Users/ingof/Dev/GitHub/matter.js/packages/matter.js/src/protocol/ExchangeManager.ts:128:13)
  2023-10-13 13:28:17.027 DEBUG ExchangeManager      Message » id: 0/57875/153890943 type: 0/64 acked: 1658110431 reqAck: true payload: 0100000000000200
  2023-10-13 13:28:17.027 DEBUG MessageExchange      Message « id: 0/57875/153890943 type: 0/64 acked: 1658110431 reqAck: true payload: 0100000000000200
  2023-10-13 13:28:17.027 DEBUG ExchangeManager      Message » id: 0/57875/1658110432 type: 0/16 acked: 153890943 reqAck: false payload: 
  2023-10-13 13:28:17.027 DEBUG MessageExchange      Message « id: 0/57875/1658110432 type: 0/16 acked: 153890943 reqAck: false payload: 

```

**Comment by Apollon77** [comment]
Usually this is a very rare case ... so please share a full log to see it if is really the same issue.
