### ISSUE TITLE
Can't run ControllerNode example in WSL2

### ISSUE THREAD

**Issue by UncleSamSwiss** [project-chip/matter.js#313]
When trying to run the ControllerNode example, under Windows Subsystem for Linux (WSL2), I get the following error:
```
/.../matter.js/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:9
    super(...args);
    ^
Error: EAFNOSUPPORT, Address family not supported by protocol
    at new BluetoothHciSocketWrapped (/.../matter.js/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:9:5)
    at new Mgmt (/.../matter.js/node_modules/@abandonware/bleno/lib/hci-socket/mgmt.js:11:20)
    at Object.<anonymous> (/.../matter.js/node_modules/@abandonware/bleno/lib/hci-socket/mgmt.js:89:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/.../matter.js/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: 97,
  code: 'EAFNOSUPPORT',
  syscall: 'socket'
}
```

When I comment out these two lines:
https://github.com/project-chip/matter.js/blob/e8317a9b83660a98642fcfbbc41892086af0f93a/packages/matter-node.js-examples/src/examples/ControllerNode.ts#L21-L22
And of course all usages of those imports, the example runs.

**Comment by Apollon77** [comment]
We need to change Bleno to a dynamic import ala Noble to prevent an "too early require".
Kind of do that https://github.com/project-chip/matter.js/blob/main/packages/matter-node-ble.js/src/ble/NobleBleClient.ts#L16-L32 for Bleno in https://github.com/project-chip/matter.js/blob/main/packages/matter-node-ble.js/src/ble/BlenoBleServer.ts#L7 too

**Comment by Apollon77** [comment]
@UncleSamSwiss Can you give it another try please?
