### ISSUE TITLE
Ignore discovered IPv4 adresses if ipv4 is disabled on network side

### ISSUE THREAD

**Issue by Apollon77** [project-chip/matter.js#315]
This should prevent a case like this where a device was discovered on IPv4 (only) but ipv4 was disabled. maybe we would also have gotten ipv6 announcements when we would have waited longer.

Aka: Configure MDNSScanner to ignore IPv4 responses if IPv4 is not configured.

```
2023-09-17 17:13:36.558 DEBUG MdnsScanner          Registered waiter for query 79988EAB5C141590-40EA020A9BDD386A._matter._tcp.local with timeout 120 seconds
2023-09-17 17:13:36.560 DEBUG MdnsScanner          Set 1 query records for query 79988EAB5C141590-40EA020A9BDD386A._matter._tcp.local: [{"name":"79988EAB5C141590-40EA020A9BDD386A._matter._tcp.local","recordClass":1,"recordType":33}]
2023-09-17 17:13:36.566 DEBUG MdnsScanner          Sending 1 query records for 1 queries with 0 known answers. Re-Announce in 1.5 seconds
2023-09-17 17:13:36.582 DEBUG UdpChannelNode       Socket created and bound  remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
2023-09-17 17:13:36.584 DEBUG UdpChannelNode       Socket created and bound  remoteAddress: undefined:5353 localAddress: :::5353
2023-09-17 17:13:36.588 DEBUG UdpChannelNode       Initialize multicast address: 192.168.178.175:5353 interface: wlan0 type: udp4
2023-09-17 17:13:36.590 DEBUG UdpChannelNode       Initialize multicast address: ::%wlan0:5353 interface: wlan0 type: udp6
2023-09-17 17:13:37.333 DEBUG MdnsScanner          Finishing waiter for query 79988EAB5C141590-40EA020A9BDD386A._matter._tcp.local, resolving: true
2023-09-17 17:13:37.338 DEBUG MdnsScanner          Removing last query 79988EAB5C141590-40EA020A9BDD386A._matter._tcp.local and stopping announce timer
2023-09-17 17:13:37.340 DEBUG MatterController     Server addresses to try: udp://192.168.178.71:5540
2023-09-17 17:13:37.341 DEBUG MatterController     Try to communicate with udp://192.168.178.71:5540 ...
2023-09-17 17:13:37.348 DEBUG MatterController     Failed to communicate with udp://192.168.178.71:5540, try next server ... IPv4 interface not initialized for port 5540. Cannot use 192.168.178.71 for pairing.
    at MatterController.pair (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:365:13)
    at /home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:354:37
    at MatterController.iterateServerAddresses (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:305:34)
    at MatterController.resume (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:350:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MatterController.connect (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:419:19)
    at async ControllerCommissioner.reconnectWithDeviceCallback (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:269:16)
    at async ControllerCommissioner.reconnectWithDevice (/home/ingof/matter.js/packages/matter.js/dist/cjs/protocol/ControllerCommissioner.js:773:30)
    at async ControllerCommissioner.executeCommissioning (/home/ingof/matter.js/packages/matter.js/dist/cjs/protocol/ControllerCommissioner.js:189:24)
    at async MatterController.commissionDevice (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:272:5)
2023-09-17 17:13:37.356 DEBUG MatterController     Server addresses to try: udp://192.168.178.71:5540,udp://192.168.178.71:5540
2023-09-17 17:13:37.357 WARN  Commission~ontroller Ble commissioning failed: Error: Failed to connect on any found server
2023-09-17 17:13:37.364 DEBUG MdnsScanner          Registered waiter for query _S0._sub._matterc._udp.local with timeout 15 seconds
2023-09-17 17:13:37.366 DEBUG MdnsScanner          Set 2 query records for query _S0._sub._matterc._udp.local: [{"name":"_matterc._udp.local","recordClass":1,"recordType":12},{"name":"_S0._sub._matterc._udp.local","recordClass":1,"recordType":12}]
2023-09-17 17:13:37.383 DEBUG MdnsScanner          Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 1.5 seconds
2023-09-17 17:13:37.744 DEBUG MdnsScanner          Found commissionable device 228451C0B53CC291._matterc._udp.local with discriminator 158/0 ...
2023-09-17 17:13:37.749 DEBUG MdnsScanner          Finishing waiter for query _S0._sub._matterc._udp.local, resolving: true
2023-09-17 17:13:37.753 DEBUG MdnsScanner          Removing last query _S0._sub._matterc._udp.local and stopping announce timer
2023-09-17 17:13:37.755 DEBUG MatterController     Server addresses to try: udp://192.168.178.71:5540
2023-09-17 17:13:37.756 DEBUG MatterController     Try to communicate with udp://192.168.178.71:5540 ...
2023-09-17 17:13:37.759 DEBUG MatterController     Failed to communicate with udp://192.168.178.71:5540, try next server ... IPv4 interface not initialized. Cannot use 192.168.178.71 for commissioning.
    at MatterController.initializePaseSecureChannel (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:228:15)
    at /home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:203:39
    at MatterController.iterateServerAddresses (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:305:34)
    at MatterController.commission (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:199:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CommissioningController.connect (/home/ingof/matter.js/packages/matter.js/dist/cjs/CommissioningController.js:119:18)
2023-09-17 17:13:37.763 DEBUG MatterController     Server addresses to try: udp://192.168.178.71:5540,udp://192.168.178.71:5540
2023-09-17 17:13:37.766 ERROR Controller           Failed to connect on any found server
    at MatterController.iterateServerAddresses (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:317:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MatterController.commission (/home/ingof/matter.js/packages/matter.js/dist/cjs/MatterController.js:199:41)
    at async CommissioningController.connect (/home/ingof/matter.js/packages/matter.js/dist/cjs/CommissioningController.js:119:18)

```

**Comment by Apollon77** [comment]
fixed by #329
