### ISSUE TITLE
commissioning error

### ISSUE THREAD

**Issue by mow** [project-chip/matter.js#319]
Hello,

currently (with https://github.com/project-chip/matter.js/tree/dd55dcd4227767471904e8f88dd87fc8f3538c16) it's not possible to communicate with the matter bridge (google home, both android latest and nesthub devices), it seems that response to a pairing request has invalid/missing value, all the bridged devices remains as offline always. 

decoded status message is;

`{ generalStatus: 1, protocolId: 0, protocolStatus: 2 }`

following are the logs;

```
2023-09-21 05:15:26.704 INFO  CaseServer           Received pairing request from udp://xxx:9558:xxx:5540
2023-09-21 05:15:26.709 DEBUG ExchangeManager      Message » id: 0/6069/2914101856 type: 0/49 acked: 40786826 reqAck: true payload: 1530012029bda67863ddcf0652d97d053900112ed50f66a6e11a1ddac0a668ba90f6444e2502127d30034104f0ad5f5df173a1626ee0b3d02a5a4c879ec88970c98001270dc0a7c26489084cb94b52f4dfc09ba6763f1850ee84709e895f04b1b37f7d06e824c0a8b63644e23104d502bbdac116cc9eaeab64734fcc395fcbc42b20c3e88e3af7fadf159fca32b208f9d214a73ebaf06c56e9630a367d70707677c1e6581011680eb0fd7e498db07ec04f9d480edde582236af2cc979680b3549e91666e1c259bc53c83e4d2a9389c8ab391de846e94e322a51573b4548b91a0a5262b2bf6f5fdfafffb9c1c6e4f8c0ab1fc627402b1d278a88e9f45e0182c7577d91189710db864cc71a51bf5f1e7bebe4816d1a013dadde1de0bead1c7c0bc6fc82db23d3e098d9dfacb9927b540d943309801d87c57db774d3dc5b78329d899bfb0586178063f319f3d487eea952d9a0a26361d5439d02cdd0433a8127b5e5545a8589a717f58435d7a1dd37683eb9d34130922bc3c3644ce651010feb01724368b700a1890527abca3206aca481da2e72848d78c56728bf355bc7efb442d31652972e3dc649ded90e2d8d64b62ac90943e0afaa07f1e4b050850965e0a798b51223f01a65b8ff82076b8f428ec125236c4613edb8a1f98116b97415276843f45b7a6c27ebe2253d6ab88ed3537565c21756dcd3af25e36a756e5cdde74c92631f1816f5b1be88801e368cea9c346c6a35cd454ddd061bc57548c2ca7e68f3110441122b3dd78db4c4970d76791a2f520d5bc5fdffa329eafd8caf8ddd45027f1dd436ebee758d5c013d2c2b26bc884bd86447ea320867eacbafc1ca75c2afa981aabf3dc054a107e3492cd5aa83b7f1ef5d18a8c7b418b0ee0281ffc15d560c064f13a8ec929c26f354409c654f1a35aa4958aa919fde94cf973bec448482bcfdc2f12beaa8a80a3149e9e8ecb462f43bed9890784232e57b26cd91f602b259c77ac5cbcbf6a2369531041afff3f05ae10823b65428507e7598ec6fa3f1acc74858809a9188884c68b1483569c56096d1a4a3a23c24b6ad7014ad75234b0c603133ea44069296224b0f6baa7719ab777337e7328f6edb448d843de2148c8621559d5cbaef496fae4e9d04b9597ad6068083d43402afaa8138a08769ef4acf5b97a1f8318
2023-09-21 05:15:26.751 DEBUG MessageExchange      Message « id: 0/6069/40786827 type: 0/16 acked: 2914101856 reqAck: false payload: 
2023-09-21 05:15:39.194 DEBUG MatterDevice         Announcing fabric: 15692912367681345142
2023-09-21 05:15:39.195 DEBUG MdnsBroadcaster      Announcement: Fabric id: dfe207740e804576/837654995 qname: xxxxxx-0000000031ED99D3._matter._tcp.local port: 5540 interface: xxx
2023-09-21 05:15:56.882 DEBUG MessageExchange      Message « id: 0/6069/40786828 type: 0/64 acked: 2914101856 reqAck: true payload: 0100000000000200
{ generalStatus: 1, protocolId: 0, protocolStatus: 2 }
2023-09-21 05:15:56.886 ERROR CaseServer           An error occurred during the commissioning (1/2) Received general error status (0)
    at CaseServerMessenger.throwIfErrorStatusReport (/home/xxx/projects/matter-new/packages/matter.js/src/protocol/securechannel/SecureChannelMessenger.ts:96:19)
    at CaseServerMessenger.nextMessage (/home/xxx/projects/matter-new/packages/matter.js/src/protocol/securechannel/SecureChannelMessenger.ts:36:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CaseServerMessenger.readSigma3 (/home/xxx/projects/matter-new/packages/matter.js/src/session/case/CaseMessenger.ts:30:29)
    at CaseServer.handleSigma1 (/home/xxx/projects/matter-new/packages/matter.js/src/session/case/CaseServer.ts:156:17)
    at CaseServer.onNewExchange (/home/xxx/projects/matter-new/packages/matter.js/src/session/case/CaseServer.ts:38:13)
    at SecureChannelProtocol.onNewExchange (/home/xxx/projects/matter-new/packages/matter.js/src/protocol/securechannel/SecureChannelProtocol.ts:38:17)
    at ExchangeManager.onMessage (/home/xxx/projects/matter-new/packages/matter.js/src/protocol/ExchangeManager.ts:126:13)
    ```

**Comment by Apollon77** [comment]
Can you please provide more details and a full log. And also: what did you do before the try? Does it also happen when you change the port? Is the 0.5.0 from npm working?

**Comment by Apollon77** [comment]
PS: Please also add when this device was paired (so with which version) ... does it work when you pair a new device?

**Comment by mow** [comment]
the last time I used matter.js/bridge device was approx. 5 months ago, so I  cloned the repo into a new folder, removed the existing bridge device from google home, and re-added the new device, I probably ran this cycle more than 30 times by modifying some logs and portions of the code, then I suspected some sort of caching, changed some settings but no luck, then I changed the productid from google console 8000 to 8001 to give it a try and problem disappeared...

**Comment by Apollon77** [comment]
can you post please how the storage directory looks like? When you check the changelog then you will notice severl breaking things in that time - especially also regarding storage and such, so there is a chance that this is simply caused by this. There migt be a chance to fix the storage entries (rename some files) and get it fixed by this ... or delete the storage and startover anew

**Comment by mow** [comment]
tried to reproduce for you, many other problems but this one I couldn't reproduce unfortunately, so I don't have anything more other than the log I pasted earlier. 

seems that this is something google mobile/cloud whatever application specific problem
