### ISSUE TITLE
Uncaught exception in MdnsServer

### ISSUE THREAD

**Issue by vves** [project-chip/matter.js#606]
On OSX when running docker containers and other virtual devices, the network interfaces list can change causing the following error.  Add a catch somewhere in the stack?

```NetworkError: Unknown interface: ap1
    at NetworkNode.getMulticastInterface (/Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter-node.js/dist/cjs/net/NetworkNode.js:37:13)
    at UdpChannelNode.create (/Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter-node.js/dist/cjs/net/UdpChannelNode.js:85:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UdpMulticastServer.createBroadcastChannel (/Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter.js/dist/cjs/net/UdpMulticastServer.js:116:12)
    at async /Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter.js/dist/cjs/net/UdpMulticastServer.js:105:24
    at async Promise.all (index 0)
    at async /Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter.js/dist/cjs/net/UdpMulticastServer.js:97:11
    at async Promise.all (index 0)
    at async UdpMulticastServer.send (/Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter.js/dist/cjs/net/UdpMulticastServer.js:94:7)
    at async MdnsServer.sendRecords (/Users/wes/Git/hd-matter-bridge/node_modules/@project-chip/matter.js/dist/cjs/mdns/MdnsServer.js:213:5)```

**Comment by Apollon77** [comment]
Thank you for the report. please repro with a current version, ideally the latest nightly

**Comment by Apollon77** [comment]
Seems to be a docker issue on macOS.  Not happening on raspi. Until we get reproduced i close here
