### ISSUE TITLE
Pairing with iOS 16.4 and iOS 16.5beta fails

### ISSUE THREAD

**Issue by lboue** [project-chip/matter.js#77]
## Pairing with iOS 16.4 fails
Pairing with iOS 16.4 fails with error message: Accessory pairing failed

```
2023-04-04 19:49:12.731 ERROR CaseServer An error occurred during the commissioning Error: Signature verification failed
    at Function.verifySpki (/home/user/matter.js/packages/matter-node.js/src/crypto/Crypto.ts:173:29)
    at CaseServer.<anonymous> (/home/user/matter.js/packages/matter-node.js/src/matter/session/secure/CaseServer.ts:98:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/matter.js/packages/matter-node.js/src/matter/session/secure/CaseServer.ts:10:58)

```

### Details

```
user@matter-vm:~/matter.js/packages/matter-node.js$ npm run matter

> @project-chip/matter-node.js@0.0.11 matter
> ts-node --project tsconfig.dist.json src/Device.ts

2023-04-04 19:48:47.914 INFO Device node-matter
2023-04-04 19:48:47.929 DEBUG MdnsBroadcaster announce commissioning mode 1 Matter test device 257 [object Object] 32768 3840
2023-04-04 19:48:47.933 INFO Device Listening
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▄▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▀▄▀▄█ █   █ █
█ █▄▄▄█ ██ ▀▀▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄▄▄▄▄▄▄█
█▄ ▄█▄ ▄▄ ▀ █  ▄▀██ █▀█
██ █▀▀ ▄▄█ █ ▀▄▄██ ▀█▀█
█▄▄████▄▄▄▀▄▀ ▀██▄▄▀▄▀█
█ ▄▄▄▄▄ █  ▄█▄█▄▄█▄ █ █
█ █   █ █▄▀▀█▄ ▄▀▀▄ ▀██
█ █▄▄▄█ █  ▀█▄█ ▀█  ▀ █
█▄▄▄▄▄▄▄█▄█▄█▄██▄██▄█▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

QR Code URL: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT:Y.K90AFN00KA0648G00
Manual pairing code: 34970112332
2023-04-04 19:49:07.126 DEBUG MessageExchange new MessageExchange 0 33825 300 5000 5
...
2023-04-04 19:49:12.653 INFO CaseServer Case server: Received pairing request from udp://fe80::85a:fd3d:ca9f:da30%ens33:56485
2023-04-04 19:49:12.657 DEBUG ExchangeManager sending id:0/33843/2398132853 t:0/49 acked:52639638 reqAck:true payload: 15300120fb625d9ec35057a01b4659f298fbc5e3b11f0a0476c86ad1570dcd5074569b2925020ca1300341044adb8015aad5b556ee8cb6ddd1b30798a2c1b5d4fbeb9d2e23b3203f42e76dec08c43aa00cf0faf32b94d6127e1aa3462083d38aca27a27f5fbe5ed30bba4e5931046301a32f458be3df4d2a47e5521a7500aa28ea91d8c27c035e97cd8f1571933aefdc7a028e3e2c454c6240c02aa4398bcbebfeb973988d92873dbfce303a5f63c28b24fd63c23b09877c0dc1b63dd51bd38ec700899082d078a55fb47a4d38bef1cdce20b7b79da8f8d78acb6ee5a8be873570605aa05e199b87b844e7e4599471b91c356adb694a8d0f175b5a0b5d89695e9343f9389dc979e3ea2f11dc3d3e66b8c5f187c84f6da63650c9973f514823ea06969e01327d95c948841a298588876a9fbb9aafae8d05a3e58438a6f57ed4118e5b0c42789daba7a436693d5a363054e75b2a55c1b742507db2b0301b029bb7c909d7df41eff984becc1a5fa142dbaaff444601d6faf7876c9181189d95258d2159eb13632defe7aedef32eccfc7b852a849e8220d19778854389357e4ed74809ce7f23749259b738316dc7020d37f6e278c94ddf55c60c7c947f0d2b02dddaa9312190d5c181134823f22a0ad88fb574091818
2023-04-04 19:49:12.730 DEBUG MessageExchange onMessageReceived 0 id:0/33843/52639639 t:0/50 acked:2398132853 reqAck:true payload: 153101540180aff63358abdd5f2d31290728a8eebb6dd3c31ff8d9ff111b7a89266057b8fc195851c34c9008a7be58fc2aac4424eb5b66fa11100a7819ea9a723c43ecca5db0082d37db150f771822936b7a5912fc8735b1e3fd37a3d1732849a0b2548aae1de09be507b2dcfac3cbe87df2468852b9f5fee43ce40cfd530d5873ab3a76c4046200393a62c1298c0a96941cefd76046793df34fa1bac713fe5000612f42315d4bb32bf62692a7200ce860341d63da746d947ea1f7ac9ce4b1fd20c3c6767b75fc7cbdb365938f2287f44a3a2ee79622d8462f605f184cc0d9615111e7024e1bd4e8f1f8fa906a6376553d77bae57782166b4cb746436f2986ac4f79b43c26945c900e4ae3321fe5ad668ae898c9aa6270b14f2125bf3266999a3a603ea4d3c64ecd03f541f9f8910d0f228638182332ce60a10a3a634ef0f9eed95b38707978e34d3e03fc93a625072f4f2a37cf3156ea59d518
2023-04-04 19:49:12.731 ERROR CaseServer An error occurred during the commissioning Error: Signature verification failed
    at Function.verifySpki (/home/user/matter.js/packages/matter-node.js/src/crypto/Crypto.ts:173:29)
    at CaseServer.<anonymous> (/home/user/matter.js/packages/matter-node.js/src/matter/session/secure/CaseServer.ts:98:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/matter.js/packages/matter-node.js/src/matter/session/secure/CaseServer.ts:10:58)
2023-04-04 19:49:12.732 DEBUG ExchangeManager sending id:0/33843/2398132854 t:0/64 acked:52639639 reqAck:true payload: 0100000000000200
2023-04-04 19:49:12.800 DEBUG MessageExchange onMessageReceived 0 id:0/33843/52639640 t:0/16 acked:2398132854 reqAck:false payload:
```

[matter-node.js-ios16.4.log](https://github.com/project-chip/matter.js/files/11151496/matter-node.js-ios16.4.log)

**Comment by Apollon77** [comment]
Interesting, I never had that error ... and used ios 16.4 too ... can you please try to restsart the device and try again?

Did you used the latest Github version?

**Comment by Apollon77** [comment]
@lboue If the error persists I have an idea and would add some more logging ...

**Comment by Apollon77** [comment]
@lboue and are you sure it is ios 16.4 and not 16.5beta1 ?

**Comment by lboue** [comment]
It fails in my case with those 3 devices:
- iOS 16.4
- iOS 16.5beta1
- iOS 16.5beta2


```
matter-vm:~/matter.js/packages/matter-node.js$ npm run matter -d
npm info using npm@9.5.0
npm info using node@v18.15.0
npm info found workspace root at /home/lboue/matter.js

> @project-chip/matter-node.js@0.0.11 matter
> ts-node --project tsconfig.dist.json src/Device.ts

2023-04-16 13:06:27.221 INFO Device node-matter
2023-04-16 13:06:27.261 DEBUG MdnsBroadcaster announce commissioning mode 1 Matter test device 257 [object Object] 32768 3840
2023-04-16 13:06:27.266 INFO Device Listening
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▄▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▀▄▀▄█ █   █ █
█ █▄▄▄█ ██ ▀▀▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄▄▄▄▄▄▄█
█▄ ▄█▄ ▄▄ ▀ █  ▄▀██ █▀█
██ █▀▀ ▄▄█ █ ▀▄▄██ ▀█▀█
█▄▄████▄▄▄▀▄▀ ▀██▄▄▀▄▀█
█ ▄▄▄▄▄ █  ▄█▄█▄▄█▄ █ █
█ █   █ █▄▀▀█▄ ▄▀▀▄ ▀██
█ █▄▄▄█ █  ▀█▄█ ▀█  ▀ █
█▄▄▄▄▄▄▄█▄█▄█▄██▄██▄█▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

QR Code URL: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT:Y.K90AFN00KA0648G00
Manual pairing code: 34970112332
2023-04-16 13:06:27.272 DEBUG UdpChannelNode initialize multicast interface 192.168.232.129 udp4 5353 ens33
2023-04-16 13:06:27.273 DEBUG UdpChannelNode initialize multicast interface ::%ens33 udp6 5353 ens33
2023-04-16 13:07:27.266 DEBUG MdnsBroadcaster announce commissioning mode 1 Matter test device 257 [object Object] 32768 3840
```

**Comment by Apollon77** [comment]
The Log is already "max verbose". If you do not get more log then this then you have an UDP/MDNS error because nothing tries to contact the library at all ... so it seems that the device s npt found or packages are not reaching the device. Check IPv6 config, firewalls, UDP package flowing correctly and no router or such is in between and such

**Comment by lboue** [comment]
Indeed, I forgot to switch the network interface of my VM back to bridge mode. Pairing succeed this time. Thanks
